
START TRANSACTION;

SET @id := (SELECT `id` FROM `fields` WHERE `key` = "lblAvailableTokens");
UPDATE `multi_lang` SET `content` = 'You can use tokens in the email messages to personalize them.<br/><br/><label>{Title}</label><label>{Name}</label><label>{Email}</label><label>{Phone}</label><label>{Country}</label><label>{City}</label><label>{State}</label><label>{Zip}</label><label>{Address}</label><label>{Company}</label><label>{Notes}</label><label>{RegNo}</label><label>{Make}</label><label>{Model}</label><label>{DtFrom}</label><label>{DtTo}</label><label>{Space}</label><label>{Extras}</label><label>{BookingID}</label><label>{UniqueID}</label><label>{Deposit}</label><label>{Total}</label><label>{Tax}</label><label>{PaymentMethod}</label><label>{CCType}</label><label>{CCNum}</label><label>{CCExp}</label><label>{CCSec}</label><label>{CancelURL}</label>' WHERE `foreign_id` = @id AND `model` = "pjField" AND `field` = "title";

UPDATE `multi_lang` SET `content` = '<p>You''ve just made a booking.<br /><br />Personal details:<br />Title: {Title}<br />Name: {Name}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br />Notes: {Notes}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Date/Time To: {DtTo}<br />Space: {Space}<br />Extras: {Extras}<br />RegNo: {RegNo}<br />Make: {Make}<br />Model: {Model}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Deposit: {Deposit}<br />Total: {Total}<br />Tax: {Tax}<br /><br />If you want to cancel your booking follow next link: {CancelURL}<br /><br />Thank you, we will contact you ASAP.</p>' WHERE `foreign_id` = 1 AND `model` = "pjOption" AND `field` = "o_email_confirmation_message";

UPDATE `multi_lang` SET `content` = '<p>You''ve just made a payment for your booking.<br /><br />Personal details:<br />Title: {Title}<br />Name: {Name}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br />Notes: {Notes}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Date/Time To: {DtTo}<br />Space: {Space}<br />Extras: {Extras}<br />RegNo: {RegNo}<br />Make: {Make}<br />Model: {Model}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Deposit: {Deposit}<br />Total: {Total}<br />Tax: {Tax}<br /><br />If you want to cancel your booking follow next link: {CancelURL}<br /><br />Thank you, we will contact you ASAP.</p>' WHERE `foreign_id` = 1 AND `model` = "pjOption" AND `field` = "o_email_payment_message";

UPDATE `multi_lang` SET `content` = '<p>You''ve just cancelled your booking.<br /><br />Personal details:<br />Title: {Title}<br />Name: {Name}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br />Notes: {Notes}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Date/Time To: {DtTo}<br />Space: {Space}<br />Extras: {Extras}<br />RegNo: {RegNo}<br />Make: {Make}<br />Model: {Model}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Deposit: {Deposit}<br />Total: {Total}<br />Tax: {Tax}<br /><br />Thank you!</p>' WHERE `foreign_id` = 1 AND `model` = "pjOption" AND `field` = "o_email_cancel_message";

UPDATE `multi_lang` SET `content` = '<p>You''ve just received a new booking.<br /><br />Personal details:<br />Title: {Title}<br />Name: {Name}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br />Notes: {Notes}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Date/Time To: {DtTo}<br />Space: {Space}<br />Extras: {Extras}<br />RegNo: {RegNo}<br />Make: {Make}<br />Model: {Model}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Deposit: {Deposit}<br />Total: {Total}<br />Tax: {Tax}<br /><br />Thank you!</p>' WHERE `foreign_id` = 1 AND `model` = "pjOption" AND `field` = "o_admin_email_confirmation_message";

UPDATE `multi_lang` SET `content` = '<p>You''ve just received a payment.<br /><br />Personal details:<br />Title: {Title}<br />Name: {Name}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br />Notes: {Notes}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Date/Time To: {DtTo}<br />Space: {Space}<br />Extras: {Extras}<br />RegNo: {RegNo}<br />Make: {Make}<br />Model: {Model}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Deposit: {Deposit}<br />Total: {Total}<br />Tax: {Tax}<br /><br /><br />Thank you!</p>' WHERE `foreign_id` = 1 AND `model` = "pjOption" AND `field` = "o_admin_email_payment_message";

UPDATE `multi_lang` SET `content` = '<p>A booking has been cancelled.<br /><br />Personal details:<br />Title: {Title}<br />Name: {Name}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br />Notes: {Notes}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Date/Time To: {DtTo}<br />Space: {Space}<br />Extras: {Extras}<br />RegNo: {RegNo}<br />Make: {Make}<br />Model: {Model}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Deposit: {Deposit}<br />Total: {Total}<br />Tax: {Tax}<br /><br /><br />Thank you!</p>' WHERE `foreign_id` = 1 AND `model` = "pjOption" AND `field` = "o_admin_email_cancel_message";

COMMIT;