/*!
 * jQuery JavaScript Library v1.7.2
 * http://jquery.com/
 *
 * Copyright 2011, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 * Copyright 2011, The Dojo Foundation
 * Released under the MIT, BSD, and GPL Licenses.
 *
 * Date: Wed Mar 21 12:46:34 2012 -0700
 */
(function(H,A){function nb(a){var b=wa[a]={},d,e;a=a.split(/\s+/);d=0;for(e=a.length;d<e;d++)b[a[d]]=true;return b}function xa(a,b,d){if(d===A&&a.nodeType===1){d="data-"+b.replace(ob,"-$1").toLowerCase();d=a.getAttribute(d);if(typeof d==="string"){try{d=d==="true"?true:d==="false"?false:d==="null"?null:c.isNumeric(d)?+d:pb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=A}return d}function la(a){for(var b in a)if(!(b==="data"&&c.isEmptyObject(a[b])))if(b!=="toJSON")return false;return true}
function ya(a,b,d){var e=b+"defer",f=b+"queue",h=b+"mark",k=c._data(a,e);if(k&&(d==="queue"||!c._data(a,f))&&(d==="mark"||!c._data(a,h)))setTimeout(function(){if(!c._data(a,f)&&!c._data(a,h)){c.removeData(a,e,true);k.fire()}},0)}function Y(){return false}function da(){return true}function za(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function Aa(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(f,h){return!!b.call(f,h,f)===d});else if(b.nodeType)return c.grep(a,function(f){return f===
b===d});else if(typeof b==="string"){var e=c.grep(a,function(f){return f.nodeType===1});if(qb.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(f){return c.inArray(f,b)>=0===d})}function Ba(a){var b=Ca.split("|");a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function rb(a){return c.nodeName(a,"table")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function Da(a,b){if(!(b.nodeType!==
1||!c.hasData(a))){var d,e,f;e=c._data(a);a=c._data(b,e);var h=e.events;if(h){delete a.handle;a.events={};for(d in h){e=0;for(f=h[d].length;e<f;e++)c.event.add(b,d,h[d][e])}}if(a.data)a.data=c.extend({},a.data)}}function Ea(a,b){var d;if(b.nodeType===1){b.clearAttributes&&b.clearAttributes();b.mergeAttributes&&b.mergeAttributes(a);d=b.nodeName.toLowerCase();if(d==="object")b.outerHTML=a.outerHTML;else if(d==="input"&&(a.type==="checkbox"||a.type==="radio")){if(a.checked)b.defaultChecked=b.checked=
a.checked;if(b.value!==a.value)b.value=a.value}else if(d==="option")b.selected=a.defaultSelected;else if(d==="input"||d==="textarea")b.defaultValue=a.defaultValue;else if(d==="script"&&b.text!==a.text)b.text=a.text;b.removeAttribute(c.expando);b.removeAttribute("_submit_attached");b.removeAttribute("_change_attached")}}function ea(a){return typeof a.getElementsByTagName!=="undefined"?a.getElementsByTagName("*"):typeof a.querySelectorAll!=="undefined"?a.querySelectorAll("*"):[]}function Fa(a){if(a.type===
"checkbox"||a.type==="radio")a.defaultChecked=a.checked}function Ga(a){var b=(a.nodeName||"").toLowerCase();if(b==="input")Fa(a);else b!=="script"&&typeof a.getElementsByTagName!=="undefined"&&c.grep(a.getElementsByTagName("input"),Fa)}function sb(a){var b=B.createElement("div");ma.appendChild(b);b.innerHTML=a.outerHTML;return b.firstChild}function Ha(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight,f=b==="width"?1:0;if(e>0){if(d!=="border")for(;f<4;f+=2){d||(e-=parseFloat(c.css(a,"padding"+
V[f]))||0);if(d==="margin")e+=parseFloat(c.css(a,d+V[f]))||0;else e-=parseFloat(c.css(a,"border"+V[f]+"Width"))||0}return e+"px"}e=Z(a,b);if(e<0||e==null)e=a.style[b];if(na.test(e))return e;e=parseFloat(e)||0;if(d)for(;f<4;f+=2){e+=parseFloat(c.css(a,"padding"+V[f]))||0;if(d!=="padding")e+=parseFloat(c.css(a,"border"+V[f]+"Width"))||0;if(d==="margin")e+=parseFloat(c.css(a,d+V[f]))||0}return e+"px"}function Ia(a){return function(b,d){if(typeof b!=="string"){d=b;b="*"}if(c.isFunction(d)){b=b.toLowerCase().split(Ja);
for(var e=0,f=b.length,h,k;e<f;e++){h=b[e];if(k=/^\+/.test(h))h=h.substr(1)||"*";h=a[h]=a[h]||[];h[k?"unshift":"push"](d)}}}}function fa(a,b,d,e,f,h){f=f||b.dataTypes[0];h=h||{};h[f]=true;f=a[f];for(var k=0,i=f?f.length:0,l=a===oa,o;k<i&&(l||!o);k++){o=f[k](b,d,e);if(typeof o==="string")if(!l||h[o])o=A;else{b.dataTypes.unshift(o);o=fa(a,b,d,e,o,h)}}if((l||!o)&&!h["*"])o=fa(a,b,d,e,"*",h);return o}function Ka(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)if(b[d]!==A)(f[d]?a:e||(e={}))[d]=
b[d];e&&c.extend(true,a,e)}function pa(a,b,d,e){if(c.isArray(b))c.each(b,function(h,k){d||tb.test(a)?e(a,k):pa(a+"["+(typeof k==="object"?h:"")+"]",k,d,e)});else if(!d&&c.type(b)==="object")for(var f in b)pa(a+"["+f+"]",b[f],d,e);else e(a,b)}function ub(a,b,d){var e=a.contents,f=a.dataTypes,h=a.responseFields,k,i,l,o;for(i in h)if(i in d)b[h[i]]=d[i];for(;f[0]==="*";){f.shift();if(k===A)k=a.mimeType||b.getResponseHeader("content-type")}if(k)for(i in e)if(e[i]&&e[i].test(k)){f.unshift(i);break}if(f[0]in
d)l=f[0];else{for(i in d){if(!f[0]||a.converters[i+" "+f[0]]){l=i;break}o||(o=i)}l=l||o}if(l){l!==f[0]&&f.unshift(l);return d[l]}}function vb(a,b){if(a.dataFilter)b=a.dataFilter(b,a.dataType);var d=a.dataTypes,e={},f,h,k=d.length,i,l=d[0],o,s,p,x,r;for(f=1;f<k;f++){if(f===1)for(h in a.converters)if(typeof h==="string")e[h.toLowerCase()]=a.converters[h];o=l;l=d[f];if(l==="*")l=o;else if(o!=="*"&&o!==l){s=o+" "+l;p=e[s]||e["* "+l];if(!p){r=A;for(x in e){i=x.split(" ");if(i[0]===o||i[0]==="*")if(r=e[i[1]+
" "+l]){x=e[x];if(x===true)p=r;else if(r===true)p=x;break}}}p||r||c.error("No conversion from "+s.replace(" "," to "));if(p!==true)b=p?p(b):r(x(b))}}return b}function La(){try{return new H.XMLHttpRequest}catch(a){}}function wb(){try{return new H.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}}function Ma(){setTimeout(xb,0);return ga=c.now()}function xb(){ga=A}function $(a,b){var d={};c.each(ha.concat.apply([],ha.slice(0,b)),function(){d[this]=a});return d}function Na(a){if(!qa[a]){var b=B.body,d=c("<"+
a+">").appendTo(b),e=d.css("display");d.remove();if(e==="none"||e===""){if(!Q){Q=B.createElement("iframe");Q.frameBorder=Q.width=Q.height=0}b.appendChild(Q);if(!aa||!Q.createElement){aa=(Q.contentWindow||Q.contentDocument).document;aa.write((c.support.boxModel?"<!doctype html>":"")+"<html><body>");aa.close()}d=aa.createElement(a);aa.body.appendChild(d);e=c.css(d,"display");b.removeChild(Q)}qa[a]=e}return qa[a]}function Oa(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}
var B=H.document,yb=H.navigator,zb=H.location,c=function(){function a(){if(!b.isReady){try{B.documentElement.doScroll("left")}catch(m){setTimeout(a,1);return}b.ready()}}var b=function(m,u){return new b.fn.init(m,u,f)},d=H.jQuery,e=H.$,f,h=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,k=/\S/,i=/^\s+/,l=/\s+$/,o=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,s=/^[\],:{}\s]*$/,p=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,x=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,r=/(?:^|:|,)(?:\s*\[)+/g,D=/(webkit)[ \/]([\w.]+)/,
I=/(opera)(?:.*version)?[ \/]([\w.]+)/,K=/(msie) ([\w.]+)/,L=/(mozilla)(?:.*? rv:([\w.]+))?/,S=/-([a-z]|[0-9])/ig,E=/^-ms-/,R=function(m,u){return(u+"").toUpperCase()},P=yb.userAgent,g,j,n=Object.prototype.toString,q=Object.prototype.hasOwnProperty,t=Array.prototype.push,v=Array.prototype.slice,z=String.prototype.trim,C=Array.prototype.indexOf,G={};b.fn=b.prototype={constructor:b,init:function(m,u,y){var w;if(!m)return this;if(m.nodeType){this.context=this[0]=m;this.length=1;return this}if(m==="body"&&
!u&&B.body){this.context=B;this[0]=B.body;this.selector=m;this.length=1;return this}if(typeof m==="string")if((w=m.charAt(0)==="<"&&m.charAt(m.length-1)===">"&&m.length>=3?[null,m,null]:h.exec(m))&&(w[1]||!u))if(w[1]){y=(u=u instanceof b?u[0]:u)?u.ownerDocument||u:B;if(m=o.exec(m))if(b.isPlainObject(u)){m=[B.createElement(m[1])];b.fn.attr.call(m,u,true)}else m=[y.createElement(m[1])];else{m=b.buildFragment([w[1]],[y]);m=(m.cacheable?b.clone(m.fragment):m.fragment).childNodes}return b.merge(this,m)}else{if((u=
B.getElementById(w[2]))&&u.parentNode){if(u.id!==w[2])return y.find(m);this.length=1;this[0]=u}this.context=B;this.selector=m;return this}else return!u||u.jquery?(u||y).find(m):this.constructor(u).find(m);else if(b.isFunction(m))return y.ready(m);if(m.selector!==A){this.selector=m.selector;this.context=m.context}return b.makeArray(m,this)},selector:"",jquery:"1.7.2",length:0,size:function(){return this.length},toArray:function(){return v.call(this,0)},get:function(m){return m==null?this.toArray():
m<0?this[this.length+m]:this[m]},pushStack:function(m,u,y){var w=this.constructor();b.isArray(m)?t.apply(w,m):b.merge(w,m);w.prevObject=this;w.context=this.context;if(u==="find")w.selector=this.selector+(this.selector?" ":"")+y;else if(u)w.selector=this.selector+"."+u+"("+y+")";return w},each:function(m,u){return b.each(this,m,u)},ready:function(m){b.bindReady();g.add(m);return this},eq:function(m){m=+m;return m===-1?this.slice(m):this.slice(m,m+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
slice:function(){return this.pushStack(v.apply(this,arguments),"slice",v.call(arguments).join(","))},map:function(m){return this.pushStack(b.map(this,function(u,y){return m.call(u,y,u)}))},end:function(){return this.prevObject||this.constructor(null)},push:t,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var m,u,y,w,J,F=arguments[0]||{},M=1,N=arguments.length,ba=false;if(typeof F==="boolean"){ba=F;F=arguments[1]||{};M=2}if(typeof F!=="object"&&!b.isFunction(F))F=
{};if(N===M){F=this;--M}for(;M<N;M++)if((m=arguments[M])!=null)for(u in m){y=F[u];w=m[u];if(F!==w)if(ba&&w&&(b.isPlainObject(w)||(J=b.isArray(w)))){if(J){J=false;y=y&&b.isArray(y)?y:[]}else y=y&&b.isPlainObject(y)?y:{};F[u]=b.extend(ba,y,w)}else if(w!==A)F[u]=w}return F};b.extend({noConflict:function(m){if(H.$===b)H.$=e;if(m&&H.jQuery===b)H.jQuery=d;return b},isReady:false,readyWait:1,holdReady:function(m){if(m)b.readyWait++;else b.ready(true)},ready:function(m){if(m===true&&!--b.readyWait||m!==true&&
!b.isReady){if(!B.body)return setTimeout(b.ready,1);b.isReady=true;if(!(m!==true&&--b.readyWait>0)){g.fireWith(B,[b]);b.fn.trigger&&b(B).trigger("ready").off("ready")}}},bindReady:function(){if(!g){g=b.Callbacks("once memory");if(B.readyState==="complete")return setTimeout(b.ready,1);if(B.addEventListener){B.addEventListener("DOMContentLoaded",j,false);H.addEventListener("load",b.ready,false)}else if(B.attachEvent){B.attachEvent("onreadystatechange",j);H.attachEvent("onload",b.ready);var m=false;
try{m=H.frameElement==null}catch(u){}B.documentElement.doScroll&&m&&a()}}},isFunction:function(m){return b.type(m)==="function"},isArray:Array.isArray||function(m){return b.type(m)==="array"},isWindow:function(m){return m!=null&&m==m.window},isNumeric:function(m){return!isNaN(parseFloat(m))&&isFinite(m)},type:function(m){return m==null?String(m):G[n.call(m)]||"object"},isPlainObject:function(m){if(!m||b.type(m)!=="object"||m.nodeType||b.isWindow(m))return false;try{if(m.constructor&&!q.call(m,"constructor")&&
!q.call(m.constructor.prototype,"isPrototypeOf"))return false}catch(u){return false}var y;for(y in m);return y===A||q.call(m,y)},isEmptyObject:function(m){for(var u in m)return false;return true},error:function(m){throw new Error(m);},parseJSON:function(m){if(typeof m!=="string"||!m)return null;m=b.trim(m);if(H.JSON&&H.JSON.parse)return H.JSON.parse(m);if(s.test(m.replace(p,"@").replace(x,"]").replace(r,"")))return(new Function("return "+m))();b.error("Invalid JSON: "+m)},parseXML:function(m){if(typeof m!==
"string"||!m)return null;var u,y;try{if(H.DOMParser){y=new DOMParser;u=y.parseFromString(m,"text/xml")}else{u=new ActiveXObject("Microsoft.XMLDOM");u.async="false";u.loadXML(m)}}catch(w){u=A}if(!u||!u.documentElement||u.getElementsByTagName("parsererror").length)b.error("Invalid XML: "+m);return u},noop:function(){},globalEval:function(m){if(m&&k.test(m))(H.execScript||function(u){H.eval.call(H,u)})(m)},camelCase:function(m){return m.replace(E,"ms-").replace(S,R)},nodeName:function(m,u){return m.nodeName&&
m.nodeName.toUpperCase()===u.toUpperCase()},each:function(m,u,y){var w,J=0,F=m.length,M=F===A||b.isFunction(m);if(y)if(M)for(w in m){if(u.apply(m[w],y)===false)break}else for(;J<F;){if(u.apply(m[J++],y)===false)break}else if(M)for(w in m){if(u.call(m[w],w,m[w])===false)break}else for(;J<F;)if(u.call(m[J],J,m[J++])===false)break;return m},trim:z?function(m){return m==null?"":z.call(m)}:function(m){return m==null?"":m.toString().replace(i,"").replace(l,"")},makeArray:function(m,u){u=u||[];if(m!=null){var y=
b.type(m);m.length==null||y==="string"||y==="function"||y==="regexp"||b.isWindow(m)?t.call(u,m):b.merge(u,m)}return u},inArray:function(m,u,y){var w;if(u){if(C)return C.call(u,m,y);w=u.length;for(y=y?y<0?Math.max(0,w+y):y:0;y<w;y++)if(y in u&&u[y]===m)return y}return-1},merge:function(m,u){var y=m.length,w=0;if(typeof u.length==="number")for(var J=u.length;w<J;w++)m[y++]=u[w];else for(;u[w]!==A;)m[y++]=u[w++];m.length=y;return m},grep:function(m,u,y){var w=[],J;y=!!y;for(var F=0,M=m.length;F<M;F++){J=
!!u(m[F],F);y!==J&&w.push(m[F])}return w},map:function(m,u,y){var w,J,F=[],M=0,N=m.length;if(m instanceof b||N!==A&&typeof N==="number"&&(N>0&&m[0]&&m[N-1]||N===0||b.isArray(m)))for(;M<N;M++){w=u(m[M],M,y);if(w!=null)F[F.length]=w}else for(J in m){w=u(m[J],J,y);if(w!=null)F[F.length]=w}return F.concat.apply([],F)},guid:1,proxy:function(m,u){if(typeof u==="string"){var y=m[u];u=m;m=y}if(b.isFunction(m)){var w=v.call(arguments,2);y=function(){return m.apply(u,w.concat(v.call(arguments)))};y.guid=m.guid=
m.guid||y.guid||b.guid++;return y}},access:function(m,u,y,w,J,F,M){var N,ba=y==null,T=0,Pa=m.length;if(y&&typeof y==="object"){for(T in y)b.access(m,u,T,y[T],1,F,w);J=1}else if(w!==A){N=M===A&&b.isFunction(w);if(ba)if(N){N=u;u=function(Ab,qc,Bb){return N.call(b(Ab),Bb)}}else{u.call(m,w);u=null}if(u)for(;T<Pa;T++)u(m[T],y,N?w.call(m[T],T,u(m[T],y)):w,M);J=1}return J?m:ba?u.call(m):Pa?u(m[0],y):F},now:function(){return(new Date).getTime()},uaMatch:function(m){m=m.toLowerCase();m=D.exec(m)||I.exec(m)||
K.exec(m)||m.indexOf("compatible")<0&&L.exec(m)||[];return{browser:m[1]||"",version:m[2]||"0"}},sub:function(){function m(y,w){return new m.fn.init(y,w)}b.extend(true,m,this);m.superclass=this;m.fn=m.prototype=this();m.fn.constructor=m;m.sub=this.sub;m.fn.init=function(y,w){if(w&&w instanceof b&&!(w instanceof m))w=m(w);return b.fn.init.call(this,y,w,u)};m.fn.init.prototype=m.fn;var u=m(B);return m},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(m,
u){G["[object "+u+"]"]=u.toLowerCase()});P=b.uaMatch(P);if(P.browser){b.browser[P.browser]=true;b.browser.version=P.version}if(b.browser.webkit)b.browser.safari=true;if(k.test("�")){i=/^[\s\xA0]+/;l=/[\s\xA0]+$/}f=b(B);if(B.addEventListener)j=function(){B.removeEventListener("DOMContentLoaded",j,false);b.ready()};else if(B.attachEvent)j=function(){if(B.readyState==="complete"){B.detachEvent("onreadystatechange",j);b.ready()}};return b}(),wa={};c.Callbacks=function(a){a=a?wa[a]||nb(a):{};var b=[],
d=[],e,f,h,k,i,l,o=function(x){var r,D,I,K;r=0;for(D=x.length;r<D;r++){I=x[r];K=c.type(I);if(K==="array")o(I);else if(K==="function")if(!a.unique||!p.has(I))b.push(I)}},s=function(x,r){r=r||[];e=!a.memory||[x,r];h=f=true;l=k||0;k=0;for(i=b.length;b&&l<i;l++)if(b[l].apply(x,r)===false&&a.stopOnFalse){e=true;break}h=false;if(b)if(a.once)if(e===true)p.disable();else b=[];else if(d&&d.length){e=d.shift();p.fireWith(e[0],e[1])}},p={add:function(){if(b){var x=b.length;o(arguments);if(h)i=b.length;else if(e&&
e!==true){k=x;s(e[0],e[1])}}return this},remove:function(){if(b)for(var x=arguments,r=0,D=x.length;r<D;r++)for(var I=0;I<b.length;I++)if(x[r]===b[I]){if(h)if(I<=i){i--;I<=l&&l--}b.splice(I--,1);if(a.unique)break}return this},has:function(x){if(b)for(var r=0,D=b.length;r<D;r++)if(x===b[r])return true;return false},empty:function(){b=[];return this},disable:function(){b=d=e=A;return this},disabled:function(){return!b},lock:function(){d=A;if(!e||e===true)p.disable();return this},locked:function(){return!d},
fireWith:function(x,r){if(d)if(h)a.once||d.push([x,r]);else a.once&&e||s(x,r);return this},fire:function(){p.fireWith(this,arguments);return this},fired:function(){return!!f}};return p};var ra=[].slice;c.extend({Deferred:function(a){var b=c.Callbacks("once memory"),d=c.Callbacks("once memory"),e=c.Callbacks("memory"),f="pending",h={resolve:b,reject:d,notify:e},k={done:b.add,fail:d.add,progress:e.add,state:function(){return f},isResolved:b.fired,isRejected:d.fired,then:function(o,s,p){i.done(o).fail(s).progress(p);
return this},always:function(){i.done.apply(i,arguments).fail.apply(i,arguments);return this},pipe:function(o,s,p){return c.Deferred(function(x){c.each({done:[o,"resolve"],fail:[s,"reject"],progress:[p,"notify"]},function(r,D){var I=D[0],K=D[1],L;c.isFunction(I)?i[r](function(){(L=I.apply(this,arguments))&&c.isFunction(L.promise)?L.promise().then(x.resolve,x.reject,x.notify):x[K+"With"](this===i?x:this,[L])}):i[r](x[K])})}).promise()},promise:function(o){if(o==null)o=k;else for(var s in k)o[s]=k[s];
return o}},i=k.promise({}),l;for(l in h){i[l]=h[l].fire;i[l+"With"]=h[l].fireWith}i.done(function(){f="resolved"},d.disable,e.lock).fail(function(){f="rejected"},b.disable,e.lock);a&&a.call(i,i);return i},when:function(a){function b(s){return function(p){e[s]=arguments.length>1?ra.call(arguments,0):p;--i||l.resolveWith(l,e)}}function d(s){return function(p){k[s]=arguments.length>1?ra.call(arguments,0):p;l.notifyWith(o,k)}}var e=ra.call(arguments,0),f=0,h=e.length,k=new Array(h),i=h,l=h<=1&&a&&c.isFunction(a.promise)?
a:c.Deferred(),o=l.promise();if(h>1){for(;f<h;f++)if(e[f]&&e[f].promise&&c.isFunction(e[f].promise))e[f].promise().then(b(f),l.reject,d(f));else--i;i||l.resolveWith(l,e)}else if(l!==a)l.resolveWith(l,h?[a]:[]);return o}});c.support=function(){var a,b,d,e,f,h,k,i,l=B.createElement("div");l.setAttribute("className","t");l.innerHTML="   <link/><table></table><a href='/a' style='top:1px;float:left;opacity:.55;'>a</a><input type='checkbox'/>";b=l.getElementsByTagName("*");d=l.getElementsByTagName("a")[0];
if(!b||!b.length||!d)return{};e=B.createElement("select");f=e.appendChild(B.createElement("option"));b=l.getElementsByTagName("input")[0];a={leadingWhitespace:l.firstChild.nodeType===3,tbody:!l.getElementsByTagName("tbody").length,htmlSerialize:!!l.getElementsByTagName("link").length,style:/top/.test(d.getAttribute("style")),hrefNormalized:d.getAttribute("href")==="/a",opacity:/^0.55/.test(d.style.opacity),cssFloat:!!d.style.cssFloat,checkOn:b.value==="on",optSelected:f.selected,getSetAttribute:l.className!==
"t",enctype:!!B.createElement("form").enctype,html5Clone:B.createElement("nav").cloneNode(true).outerHTML!=="<:nav></:nav>",submitBubbles:true,changeBubbles:true,focusinBubbles:false,deleteExpando:true,noCloneEvent:true,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableMarginRight:true,pixelMargin:true};c.boxModel=a.boxModel=B.compatMode==="CSS1Compat";b.checked=true;a.noCloneChecked=b.cloneNode(true).checked;e.disabled=true;a.optDisabled=!f.disabled;try{delete l.test}catch(o){a.deleteExpando=
false}if(!l.addEventListener&&l.attachEvent&&l.fireEvent){l.attachEvent("onclick",function(){a.noCloneEvent=false});l.cloneNode(true).fireEvent("onclick")}b=B.createElement("input");b.value="t";b.setAttribute("type","radio");a.radioValue=b.value==="t";b.setAttribute("checked","checked");b.setAttribute("name","t");l.appendChild(b);d=B.createDocumentFragment();d.appendChild(l.lastChild);a.checkClone=d.cloneNode(true).cloneNode(true).lastChild.checked;a.appendChecked=b.checked;d.removeChild(b);d.appendChild(l);
if(l.attachEvent)for(k in{submit:1,change:1,focusin:1}){b="on"+k;i=b in l;if(!i){l.setAttribute(b,"return;");i=typeof l[b]==="function"}a[k+"Bubbles"]=i}d.removeChild(l);d=e=f=l=b=null;c(function(){var s,p,x,r,D=B.getElementsByTagName("body")[0];if(D){s=B.createElement("div");s.style.cssText="padding:0;margin:0;border:0;visibility:hidden;width:0;height:0;position:static;top:0;margin-top:1px";D.insertBefore(s,D.firstChild);l=B.createElement("div");s.appendChild(l);l.innerHTML="<table><tr><td style='padding:0;margin:0;border:0;display:none'></td><td>t</td></tr></table>";
h=l.getElementsByTagName("td");i=h[0].offsetHeight===0;h[0].style.display="";h[1].style.display="none";a.reliableHiddenOffsets=i&&h[0].offsetHeight===0;if(H.getComputedStyle){l.innerHTML="";p=B.createElement("div");p.style.width="0";p.style.marginRight="0";l.style.width="2px";l.appendChild(p);a.reliableMarginRight=(parseInt((H.getComputedStyle(p,null)||{marginRight:0}).marginRight,10)||0)===0}if(typeof l.style.zoom!=="undefined"){l.innerHTML="";l.style.width=l.style.padding="1px";l.style.border=0;
l.style.overflow="hidden";l.style.display="inline";l.style.zoom=1;a.inlineBlockNeedsLayout=l.offsetWidth===3;l.style.display="block";l.style.overflow="visible";l.innerHTML="<div style='width:5px;'></div>";a.shrinkWrapBlocks=l.offsetWidth!==3}l.style.cssText="position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:0;visibility:hidden;";l.innerHTML="<div style='position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:5px solid #000;display:block;'><div style='padding:0;margin:0;border:0;display:block;overflow:hidden;'></div></div><table style='position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:5px solid #000;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
p=l.firstChild;x=p.firstChild;r={doesNotAddBorder:x.offsetTop!==5,doesAddBorderForTableAndCells:p.nextSibling.firstChild.firstChild.offsetTop===5};x.style.position="fixed";x.style.top="20px";r.fixedPosition=x.offsetTop===20||x.offsetTop===15;x.style.position=x.style.top="";p.style.overflow="hidden";p.style.position="relative";r.subtractsBorderForOverflowNotVisible=x.offsetTop===-5;r.doesNotIncludeMarginInBodyOffset=D.offsetTop!==1;if(H.getComputedStyle){l.style.marginTop="1%";a.pixelMargin=(H.getComputedStyle(l,
null)||{marginTop:0}).marginTop!=="1%"}if(typeof s.style.zoom!=="undefined")s.style.zoom=1;D.removeChild(s);l=null;c.extend(a,r)}});return a}();var pb=/^(?:\{.*\}|\[.*\])$/,ob=/([A-Z])/g;c.extend({cache:{},uuid:0,expando:"jQuery"+(c.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!la(a)},data:function(a,b,d,e){if(c.acceptData(a)){var f;f=c.expando;
var h=typeof b==="string",k=a.nodeType,i=k?c.cache:a,l=k?a[f]:a[f]&&f,o=b==="events";if(!((!l||!i[l]||!o&&!e&&!i[l].data)&&h&&d===A)){if(!l)if(k)a[f]=l=++c.uuid;else l=f;if(!i[l]){i[l]={};if(!k)i[l].toJSON=c.noop}if(typeof b==="object"||typeof b==="function")if(e)i[l]=c.extend(i[l],b);else i[l].data=c.extend(i[l].data,b);f=a=i[l];if(!e){if(!a.data)a.data={};a=a.data}if(d!==A)a[c.camelCase(b)]=d;if(o&&!a[b])return f.events;if(h){d=a[b];if(d==null)d=a[c.camelCase(b)]}else d=a;return d}}},removeData:function(a,
b,d){if(c.acceptData(a)){var e,f,h,k=c.expando,i=a.nodeType,l=i?c.cache:a,o=i?a[k]:k;if(l[o]){if(b)if(e=d?l[o]:l[o].data){if(!c.isArray(b))if(b in e)b=[b];else{b=c.camelCase(b);b=b in e?[b]:b.split(" ")}f=0;for(h=b.length;f<h;f++)delete e[b[f]];if(!(d?la:c.isEmptyObject)(e))return}if(!d){delete l[o].data;if(!la(l[o]))return}if(c.support.deleteExpando||!l.setInterval)delete l[o];else l[o]=null;if(i)if(c.support.deleteExpando)delete a[k];else if(a.removeAttribute)a.removeAttribute(k);else a[k]=null}}},
_data:function(a,b,d){return c.data(a,b,d,true)},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){var d,e,f,h,k,i=this[0],l=0,o=null;if(a===A){if(this.length){o=c.data(i);if(i.nodeType===1&&!c._data(i,"parsedAttrs")){f=i.attributes;for(k=f.length;l<k;l++){h=f[l].name;if(h.indexOf("data-")===0){h=c.camelCase(h.substring(5));xa(i,h,o[h])}}c._data(i,"parsedAttrs",true)}}return o}if(typeof a===
"object")return this.each(function(){c.data(this,a)});d=a.split(".",2);d[1]=d[1]?"."+d[1]:"";e=d[1]+"!";return c.access(this,function(s){if(s===A){o=this.triggerHandler("getData"+e,[d[0]]);if(o===A&&i){o=c.data(i,a);o=xa(i,a,o)}return o===A&&d[1]?this.data(d[0]):o}d[1]=s;this.each(function(){var p=c(this);p.triggerHandler("setData"+e,d);c.data(this,a,s);p.triggerHandler("changeData"+e,d)})},null,b,arguments.length>1,null,false)},removeData:function(a){return this.each(function(){c.removeData(this,
a)})}});c.extend({_mark:function(a,b){if(a){b=(b||"fx")+"mark";c._data(a,b,(c._data(a,b)||0)+1)}},_unmark:function(a,b,d){if(a!==true){d=b;b=a;a=false}if(b){d=d||"fx";var e=d+"mark";if(a=a?0:(c._data(b,e)||1)-1)c._data(b,e,a);else{c.removeData(b,e,true);ya(b,d,"mark")}}},queue:function(a,b,d){var e;if(a){b=(b||"fx")+"queue";e=c._data(a,b);if(d)if(!e||c.isArray(d))e=c._data(a,b,c.makeArray(d));else e.push(d);return e||[]}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.shift(),f={};if(e===
"inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");c._data(a,b+".run",f);e.call(a,function(){c.dequeue(a,b)},f)}if(!d.length){c.removeData(a,b+"queue "+b+".run",true);ya(a,b,"queue")}}});c.fn.extend({queue:function(a,b){var d=2;if(typeof a!=="string"){b=a;a="fx";d--}if(arguments.length<d)return c.queue(this[0],a);return b===A?this:this.each(function(){var e=c.queue(this,a,b);a==="fx"&&e[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,
a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(d,e){var f=setTimeout(d,a);e.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){function d(){--k||e.resolveWith(f,[f])}if(typeof a!=="string"){b=a;a=A}a=a||"fx";var e=c.Deferred(),f=this,h=f.length,k=1,i=a+"defer",l=a+"queue";a=a+"mark";for(var o;h--;)if(o=c.data(f[h],i,A,true)||(c.data(f[h],l,A,true)||c.data(f[h],a,A,true))&&c.data(f[h],i,c.Callbacks("once memory"),
true)){k++;o.add(d)}d();return e.promise(b)}});var Qa=/[\n\t\r]/g,ia=/\s+/,Cb=/\r/g,Db=/^(?:button|input)$/i,Eb=/^(?:button|input|object|select|textarea)$/i,Fb=/^a(?:rea)?$/i,Ra=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,Sa=c.support.getSetAttribute,U,Ta,Ua;c.fn.extend({attr:function(a,b){return c.access(this,c.attr,a,b,arguments.length>1)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},
prop:function(a,b){return c.access(this,c.prop,a,b,arguments.length>1)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=A;delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f,h,k,i;if(c.isFunction(a))return this.each(function(l){c(this).addClass(a.call(this,l,this.className))});if(a&&typeof a==="string"){b=a.split(ia);d=0;for(e=this.length;d<e;d++){f=this[d];if(f.nodeType===1)if(!f.className&&b.length===1)f.className=a;else{h=" "+f.className+" ";k=0;for(i=
b.length;k<i;k++)~h.indexOf(" "+b[k]+" ")||(h+=b[k]+" ");f.className=c.trim(h)}}}return this},removeClass:function(a){var b,d,e,f,h,k,i;if(c.isFunction(a))return this.each(function(l){c(this).removeClass(a.call(this,l,this.className))});if(a&&typeof a==="string"||a===A){b=(a||"").split(ia);d=0;for(e=this.length;d<e;d++){f=this[d];if(f.nodeType===1&&f.className)if(a){h=(" "+f.className+" ").replace(Qa," ");k=0;for(i=b.length;k<i;k++)h=h.replace(" "+b[k]+" "," ");f.className=c.trim(h)}else f.className=
""}}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(f){c(this).toggleClass(a.call(this,f,this.className,b),b)});return this.each(function(){if(d==="string")for(var f,h=0,k=c(this),i=b,l=a.split(ia);f=l[h++];){i=e?i:!k.hasClass(f);k[i?"addClass":"removeClass"](f)}else if(d==="undefined"||d==="boolean"){this.className&&c._data(this,"__className__",this.className);this.className=this.className||a===false?"":c._data(this,"__className__")||
""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1&&(" "+this[b].className+" ").replace(Qa," ").indexOf(a)>-1)return true;return false},val:function(a){var b,d,e,f=this[0];if(arguments.length){e=c.isFunction(a);return this.each(function(h){var k=c(this);if(this.nodeType===1){h=e?a.call(this,h,k.val()):a;if(h==null)h="";else if(typeof h==="number")h+="";else if(c.isArray(h))h=c.map(h,function(i){return i==null?"":i+""});b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()];
if(!b||!("set"in b)||b.set(this,h,"value")===A)this.value=h}})}else if(f){if((b=c.valHooks[f.type]||c.valHooks[f.nodeName.toLowerCase()])&&"get"in b&&(d=b.get(f,"value"))!==A)return d;d=f.value;return typeof d==="string"?d.replace(Cb,""):d==null?"":d}}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b,d,e=a.selectedIndex,f=[],h=a.options,k=a.type==="select-one";if(e<0)return null;a=k?e:0;for(d=k?e+1:h.length;a<
d;a++){b=h[a];if(b.selected&&(c.support.optDisabled?!b.disabled:b.getAttribute("disabled")===null)&&(!b.parentNode.disabled||!c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(k)return b;f.push(b)}}if(k&&!f.length&&h.length)return c(h[e]).val();return f},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=c.inArray(c(this).val(),d)>=0});if(!d.length)a.selectedIndex=-1;return d}}},attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,
offset:true},attr:function(a,b,d,e){var f,h,k=a.nodeType;if(!(!a||k===3||k===8||k===2)){if(e&&b in c.attrFn)return c(a)[b](d);if(typeof a.getAttribute==="undefined")return c.prop(a,b,d);if(e=k!==1||!c.isXMLDoc(a)){b=b.toLowerCase();h=c.attrHooks[b]||(Ra.test(b)?Ta:U)}if(d!==A)if(d===null)c.removeAttr(a,b);else if(h&&"set"in h&&e&&(f=h.set(a,d,b))!==A)return f;else{a.setAttribute(b,""+d);return d}else if(h&&"get"in h&&e&&(f=h.get(a,b))!==null)return f;else{f=a.getAttribute(b);return f===null?A:f}}},
removeAttr:function(a,b){var d,e,f,h,k=0;if(b&&a.nodeType===1){d=b.toLowerCase().split(ia);for(f=d.length;k<f;k++)if(e=d[k]){b=c.propFix[e]||e;(h=Ra.test(e))||c.attr(a,e,"");a.removeAttribute(Sa?e:b);if(h&&b in a)a[b]=false}}},attrHooks:{type:{set:function(a,b){if(Db.test(a.nodeName)&&a.parentNode)c.error("type property can't be changed");else if(!c.support.radioValue&&b==="radio"&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);if(d)a.value=d;return b}}},value:{get:function(a,b){if(U&&
c.nodeName(a,"button"))return U.get(a,b);return b in a?a.value:null},set:function(a,b,d){if(U&&c.nodeName(a,"button"))return U.set(a,b,d);a.value=b}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,d){var e,f,h=a.nodeType;if(!(!a||h===3||h===8||h===2)){if(h!==
1||!c.isXMLDoc(a)){b=c.propFix[b]||b;f=c.propHooks[b]}return d!==A?f&&"set"in f&&(e=f.set(a,d,b))!==A?e:(a[b]=d):f&&"get"in f&&(e=f.get(a,b))!==null?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Eb.test(a.nodeName)||Fb.test(a.nodeName)&&a.href?0:A}}}});c.attrHooks.tabindex=c.propHooks.tabIndex;Ta={get:function(a,b){var d,e=c.prop(a,b);return e===true||typeof e!=="boolean"&&(d=a.getAttributeNode(b))&&d.nodeValue!==false?
b.toLowerCase():A},set:function(a,b,d){if(b===false)c.removeAttr(a,d);else{b=c.propFix[d]||d;if(b in a)a[b]=true;a.setAttribute(d,d.toLowerCase())}return d}};if(!Sa){Ua={name:true,id:true,coords:true};U=c.valHooks.button={get:function(a,b){return(a=a.getAttributeNode(b))&&(Ua[b]?a.nodeValue!=="":a.specified)?a.nodeValue:A},set:function(a,b,d){var e=a.getAttributeNode(d);if(!e){e=B.createAttribute(d);a.setAttributeNode(e)}return e.nodeValue=b+""}};c.attrHooks.tabindex.set=U.set;c.each(["width","height"],
function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(d,e){if(e===""){d.setAttribute(b,"auto");return e}}})});c.attrHooks.contenteditable={get:U.get,set:function(a,b,d){if(b==="")b="false";U.set(a,b,d)}}}c.support.hrefNormalized||c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(d){d=d.getAttribute(b,2);return d===null?A:d}})});if(!c.support.style)c.attrHooks.style={get:function(a){return a.style.cssText.toLowerCase()||A},set:function(a,
b){return a.style.cssText=""+b}};if(!c.support.optSelected)c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(){return null}});if(!c.support.enctype)c.propFix.enctype="encoding";c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return a.getAttribute("value")===null?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=c.inArray(c(a).val(),b)>=0}})});
var sa=/^(?:textarea|input|select)$/i,Va=/^([^\.]*)?(?:\.(.+))?$/,Gb=/(?:^|\s)hover(\.\S+)?\b/,Hb=/^key/,Ib=/^(?:mouse|contextmenu)|click/,Wa=/^(?:focusinfocus|focusoutblur)$/,Jb=/^(\w*)(?:#([\w\-]+))?(?:\.([\w\-]+))?$/,Kb=function(a){if(a=Jb.exec(a)){a[1]=(a[1]||"").toLowerCase();a[3]=a[3]&&new RegExp("(?:^|\\s)"+a[3]+"(?:\\s|$)")}return a},Lb=function(a,b){var d=a.attributes||{};return(!b[1]||a.nodeName.toLowerCase()===b[1])&&(!b[2]||(d.id||{}).value===b[2])&&(!b[3]||b[3].test((d["class"]||{}).value))},
Xa=function(a){return c.event.special.hover?a:a.replace(Gb,"mouseenter$1 mouseleave$1")};c.event={add:function(a,b,d,e,f){var h,k,i,l,o,s,p,x,r;if(!(a.nodeType===3||a.nodeType===8||!b||!d||!(h=c._data(a)))){if(d.handler){p=d;d=p.handler;f=p.selector}if(!d.guid)d.guid=c.guid++;i=h.events;if(!i)h.events=i={};k=h.handle;if(!k){h.handle=k=function(D){return typeof c!=="undefined"&&(!D||c.event.triggered!==D.type)?c.event.dispatch.apply(k.elem,arguments):A};k.elem=a}b=c.trim(Xa(b)).split(" ");for(h=0;h<
b.length;h++){l=Va.exec(b[h])||[];o=l[1];s=(l[2]||"").split(".").sort();r=c.event.special[o]||{};o=(f?r.delegateType:r.bindType)||o;r=c.event.special[o]||{};l=c.extend({type:o,origType:l[1],data:e,handler:d,guid:d.guid,selector:f,quick:f&&Kb(f),namespace:s.join(".")},p);x=i[o];if(!x){x=i[o]=[];x.delegateCount=0;if(!r.setup||r.setup.call(a,e,s,k)===false)if(a.addEventListener)a.addEventListener(o,k,false);else a.attachEvent&&a.attachEvent("on"+o,k)}if(r.add){r.add.call(a,l);if(!l.handler.guid)l.handler.guid=
d.guid}f?x.splice(x.delegateCount++,0,l):x.push(l);c.event.global[o]=true}a=null}},global:{},remove:function(a,b,d,e,f){var h=c.hasData(a)&&c._data(a),k,i,l,o,s,p,x,r,D,I;if(h&&(x=h.events)){b=c.trim(Xa(b||"")).split(" ");for(k=0;k<b.length;k++){i=Va.exec(b[k])||[];l=o=i[1];i=i[2];if(l){r=c.event.special[l]||{};l=(e?r.delegateType:r.bindType)||l;D=x[l]||[];s=D.length;i=i?new RegExp("(^|\\.)"+i.split(".").sort().join("\\.(?:.*\\.)?")+"(\\.|$)"):null;for(p=0;p<D.length;p++){I=D[p];if((f||o===I.origType)&&
(!d||d.guid===I.guid)&&(!i||i.test(I.namespace))&&(!e||e===I.selector||e==="**"&&I.selector)){D.splice(p--,1);I.selector&&D.delegateCount--;r.remove&&r.remove.call(a,I)}}if(D.length===0&&s!==D.length){if(!r.teardown||r.teardown.call(a,i)===false)c.removeEvent(a,l,h.handle);delete x[l]}}else for(l in x)c.event.remove(a,l+b[k],d,e,true)}if(c.isEmptyObject(x)){if(b=h.handle)b.elem=null;c.removeData(a,["events","handle"],true)}}},customEvent:{getData:true,setData:true,changeData:true},trigger:function(a,
b,d,e){if(!(d&&(d.nodeType===3||d.nodeType===8))){var f=a.type||a,h=[],k,i,l,o,s;if(!Wa.test(f+c.event.triggered)){if(f.indexOf("!")>=0){f=f.slice(0,-1);k=true}if(f.indexOf(".")>=0){h=f.split(".");f=h.shift();h.sort()}if(!((!d||c.event.customEvent[f])&&!c.event.global[f])){a=typeof a==="object"?a[c.expando]?a:new c.Event(f,a):new c.Event(f);a.type=f;a.isTrigger=true;a.exclusive=k;a.namespace=h.join(".");a.namespace_re=a.namespace?new RegExp("(^|\\.)"+h.join("\\.(?:.*\\.)?")+"(\\.|$)"):null;k=f.indexOf(":")<
0?"on"+f:"";if(d){a.result=A;if(!a.target)a.target=d;b=b!=null?c.makeArray(b):[];b.unshift(a);l=c.event.special[f]||{};if(!(l.trigger&&l.trigger.apply(d,b)===false)){s=[[d,l.bindType||f]];if(!e&&!l.noBubble&&!c.isWindow(d)){o=l.delegateType||f;h=Wa.test(o+f)?d:d.parentNode;for(i=null;h;h=h.parentNode){s.push([h,o]);i=h}if(i&&i===d.ownerDocument)s.push([i.defaultView||i.parentWindow||H,o])}for(i=0;i<s.length&&!a.isPropagationStopped();i++){h=s[i][0];a.type=s[i][1];(o=(c._data(h,"events")||{})[a.type]&&
c._data(h,"handle"))&&o.apply(h,b);(o=k&&h[k])&&c.acceptData(h)&&o.apply(h,b)===false&&a.preventDefault()}a.type=f;if(!e&&!a.isDefaultPrevented())if((!l._default||l._default.apply(d.ownerDocument,b)===false)&&!(f==="click"&&c.nodeName(d,"a"))&&c.acceptData(d))if(k&&d[f]&&(f!=="focus"&&f!=="blur"||a.target.offsetWidth!==0)&&!c.isWindow(d)){if(i=d[k])d[k]=null;c.event.triggered=f;d[f]();c.event.triggered=A;if(i)d[k]=i}return a.result}}else{d=c.cache;for(i in d)d[i].events&&d[i].events[f]&&c.event.trigger(a,
b,d[i].handle.elem,true)}}}}},dispatch:function(a){a=c.event.fix(a||H.event);var b=(c._data(this,"events")||{})[a.type]||[],d=b.delegateCount,e=[].slice.call(arguments,0),f=!a.exclusive&&!a.namespace,h=c.event.special[a.type]||{},k=[],i,l,o,s,p,x,r;e[0]=a;a.delegateTarget=this;if(!(h.preDispatch&&h.preDispatch.call(this,a)===false)){if(d&&!(a.button&&a.type==="click")){o=c(this);o.context=this.ownerDocument||this;for(l=a.target;l!=this;l=l.parentNode||this)if(l.disabled!==true){p={};x=[];o[0]=l;for(i=
0;i<d;i++){s=b[i];r=s.selector;if(p[r]===A)p[r]=s.quick?Lb(l,s.quick):o.is(r);p[r]&&x.push(s)}x.length&&k.push({elem:l,matches:x})}}b.length>d&&k.push({elem:this,matches:b.slice(d)});for(i=0;i<k.length&&!a.isPropagationStopped();i++){d=k[i];a.currentTarget=d.elem;for(b=0;b<d.matches.length&&!a.isImmediatePropagationStopped();b++){s=d.matches[b];if(f||!a.namespace&&!s.namespace||a.namespace_re&&a.namespace_re.test(s.namespace)){a.data=s.data;a.handleObj=s;s=((c.event.special[s.origType]||{}).handle||
s.handler).apply(d.elem,e);if(s!==A){a.result=s;if(s===false){a.preventDefault();a.stopPropagation()}}}}}h.postDispatch&&h.postDispatch.call(this,a);return a.result}},props:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:"char charCode key keyCode".split(" "),filter:function(a,b){if(a.which==null)a.which=b.charCode!=null?b.charCode:b.keyCode;return a}},
mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var d,e,f=b.button,h=b.fromElement;if(a.pageX==null&&b.clientX!=null){d=a.target.ownerDocument||B;e=d.documentElement;d=d.body;a.pageX=b.clientX+(e&&e.scrollLeft||d&&d.scrollLeft||0)-(e&&e.clientLeft||d&&d.clientLeft||0);a.pageY=b.clientY+(e&&e.scrollTop||d&&d.scrollTop||0)-(e&&e.clientTop||d&&d.clientTop||0)}if(!a.relatedTarget&&h)a.relatedTarget=h===
a.target?b.toElement:h;if(!a.which&&f!==A)a.which=f&1?1:f&2?3:f&4?2:0;return a}},fix:function(a){if(a[c.expando])return a;var b,d,e=a,f=c.event.fixHooks[a.type]||{},h=f.props?this.props.concat(f.props):this.props;a=c.Event(e);for(b=h.length;b;){d=h[--b];a[d]=e[d]}if(!a.target)a.target=e.srcElement||B;if(a.target.nodeType===3)a.target=a.target.parentNode;if(a.metaKey===A)a.metaKey=a.ctrlKey;return f.filter?f.filter(a,e):a},special:{ready:{setup:c.bindReady},load:{noBubble:true},focus:{delegateType:"focusin"},
blur:{delegateType:"focusout"},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:true,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.event.handle=c.event.dispatch;c.removeEvent=B.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,
d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);if(a&&a.type){this.originalEvent=a;this.type=a.type;this.isDefaultPrevented=a.defaultPrevented||a.returnValue===false||a.getPreventDefault&&a.getPreventDefault()?da:Y}else this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=da;var a=this.originalEvent;
if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=da;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=da;this.stopPropagation()},isDefaultPrevented:Y,isPropagationStopped:Y,isImmediatePropagationStopped:Y};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,
handle:function(d){var e=this,f=d.relatedTarget,h=d.handleObj,k;if(!f||f!==e&&!c.contains(e,f)){d.type=h.origType;k=h.handler.apply(this,arguments);d.type=b}return k}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return false;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;if((a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:A)&&!a._submit_attached){c.event.add(a,"submit._submit",function(b){b._submit_bubble=true});
a._submit_attached=true}})},postDispatch:function(a){if(a._submit_bubble){delete a._submit_bubble;this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,true)}},teardown:function(){if(c.nodeName(this,"form"))return false;c.event.remove(this,"._submit")}};if(!c.support.changeBubbles)c.event.special.change={setup:function(){if(sa.test(this.nodeName)){if(this.type==="checkbox"||this.type==="radio"){c.event.add(this,"propertychange._change",function(a){if(a.originalEvent.propertyName===
"checked")this._just_changed=true});c.event.add(this,"click._change",function(a){if(this._just_changed&&!a.isTrigger){this._just_changed=false;c.event.simulate("change",this,a,true)}})}return false}c.event.add(this,"beforeactivate._change",function(a){a=a.target;if(sa.test(a.nodeName)&&!a._change_attached){c.event.add(a,"change._change",function(b){this.parentNode&&!b.isSimulated&&!b.isTrigger&&c.event.simulate("change",this.parentNode,b,true)});a._change_attached=true}})},handle:function(a){var b=
a.target;if(this!==b||a.isSimulated||a.isTrigger||b.type!=="radio"&&b.type!=="checkbox")return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return sa.test(this.nodeName)}};c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(f){c.event.simulate(b,f.target,c.event.fix(f),true)};c.event.special[b]={setup:function(){d++===0&&B.addEventListener(a,e,true)},teardown:function(){--d===0&&B.removeEventListener(a,
e,true)}}});c.fn.extend({on:function(a,b,d,e,f){var h,k;if(typeof a==="object"){if(typeof b!=="string"){d=d||b;b=A}for(k in a)this.on(k,b,d,a[k],f);return this}if(d==null&&e==null){e=b;d=b=A}else if(e==null)if(typeof b==="string"){e=d;d=A}else{e=d;d=b;b=A}if(e===false)e=Y;else if(!e)return this;if(f===1){h=e;e=function(i){c().off(i);return h.apply(this,arguments)};e.guid=h.guid||(h.guid=c.guid++)}return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,d,e){return this.on(a,b,d,e,
1)},off:function(a,b,d){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if(typeof a==="object"){for(e in a)this.off(e,b,a[e]);return this}if(b===false||typeof b==="function"){d=b;b=A}if(d===false)d=Y;return this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,d){return this.on(a,null,b,d)},unbind:function(a,b){return this.off(a,null,b)},live:function(a,b,d){c(this.context).on(a,
this.selector,b,d);return this},die:function(a,b){c(this.context).off(a,this.selector||"**",b);return this},delegate:function(a,b,d,e){return this.on(b,a,d,e)},undelegate:function(a,b,d){return arguments.length==1?this.off(a,"**"):this.off(b,a,d)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0])return c.event.trigger(a,b,this[0],true)},toggle:function(a){var b=arguments,d=a.guid||c.guid++,e=0,f=function(h){var k=(c._data(this,
"lastToggle"+a.guid)||0)%e;c._data(this,"lastToggle"+a.guid,k+1);h.preventDefault();return b[k].apply(this,arguments)||false};for(f.guid=d;e<b.length;)b[e++].guid=d;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){c.fn[b]=function(d,
e){if(e==null){e=d;d=null}return arguments.length>0?this.on(b,null,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true;if(Hb.test(b))c.event.fixHooks[b]=c.event.keyHooks;if(Ib.test(b))c.event.fixHooks[b]=c.event.mouseHooks});(function(){function a(g,j,n,q,t,v){t=0;for(var z=q.length;t<z;t++){var C=q[t];if(C){var G=false;for(C=C[g];C;){if(C[e]===n){G=q[C.sizset];break}if(C.nodeType===1&&!v){C[e]=n;C.sizset=t}if(C.nodeName.toLowerCase()===j){G=C;break}C=C[g]}q[t]=G}}}function b(g,j,n,q,t,v){t=0;for(var z=
q.length;t<z;t++){var C=q[t];if(C){var G=false;for(C=C[g];C;){if(C[e]===n){G=q[C.sizset];break}if(C.nodeType===1){if(!v){C[e]=n;C.sizset=t}if(typeof j!=="string"){if(C===j){G=true;break}}else if(p.filter(j,[C]).length>0){G=C;break}}C=C[g]}q[t]=G}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e="sizcache"+(Math.random()+"").replace(".",""),f=0,h=Object.prototype.toString,k=false,i=true,l=/\\/g,o=/\r\n/g,
s=/\W/;[0,0].sort(function(){i=false;return 0});var p=function(g,j,n,q){n=n||[];var t=j=j||B;if(j.nodeType!==1&&j.nodeType!==9)return[];if(!g||typeof g!=="string")return n;var v,z,C,G,m,u=true,y=p.isXML(j),w=[],J=g;do{d.exec("");if(v=d.exec(J)){J=v[3];w.push(v[1]);if(v[2]){G=v[3];break}}}while(v);if(w.length>1&&D.exec(g))if(w.length===2&&r.relative[w[0]])z=P(w[0]+w[1],j,q);else for(z=r.relative[w[0]]?[j]:p(w.shift(),j);w.length;){g=w.shift();if(r.relative[g])g+=w.shift();z=P(g,z,q)}else{if(!q&&w.length>
1&&j.nodeType===9&&!y&&r.match.ID.test(w[0])&&!r.match.ID.test(w[w.length-1])){v=p.find(w.shift(),j,y);j=v.expr?p.filter(v.expr,v.set)[0]:v.set[0]}if(j){v=q?{expr:w.pop(),set:L(q)}:p.find(w.pop(),w.length===1&&(w[0]==="~"||w[0]==="+")&&j.parentNode?j.parentNode:j,y);z=v.expr?p.filter(v.expr,v.set):v.set;if(w.length>0)C=L(z);else u=false;for(;w.length;){v=m=w.pop();if(r.relative[m])v=w.pop();else m="";if(v==null)v=j;r.relative[m](C,v,y)}}else C=[]}C||(C=z);C||p.error(m||g);if(h.call(C)==="[object Array]")if(u)if(j&&
j.nodeType===1)for(g=0;C[g]!=null;g++){if(C[g]&&(C[g]===true||C[g].nodeType===1&&p.contains(j,C[g])))n.push(z[g])}else for(g=0;C[g]!=null;g++)C[g]&&C[g].nodeType===1&&n.push(z[g]);else n.push.apply(n,C);else L(C,n);if(G){p(G,t,n,q);p.uniqueSort(n)}return n};p.uniqueSort=function(g){if(E){k=i;g.sort(E);if(k)for(var j=1;j<g.length;j++)g[j]===g[j-1]&&g.splice(j--,1)}return g};p.matches=function(g,j){return p(g,null,null,j)};p.matchesSelector=function(g,j){return p(j,null,null,[g]).length>0};p.find=function(g,
j,n){var q,t,v,z,C,G;if(!g)return[];t=0;for(v=r.order.length;t<v;t++){C=r.order[t];if(z=r.leftMatch[C].exec(g)){G=z[1];z.splice(1,1);if(G.substr(G.length-1)!=="\\"){z[1]=(z[1]||"").replace(l,"");q=r.find[C](z,j,n);if(q!=null){g=g.replace(r.match[C],"");break}}}}q||(q=typeof j.getElementsByTagName!=="undefined"?j.getElementsByTagName("*"):[]);return{set:q,expr:g}};p.filter=function(g,j,n,q){for(var t,v,z,C,G,m,u,y,w=g,J=[],F=j,M=j&&j[0]&&p.isXML(j[0]);g&&j.length;){for(z in r.filter)if((t=r.leftMatch[z].exec(g))!=
null&&t[2]){m=r.filter[z];G=t[1];v=false;t.splice(1,1);if(G.substr(G.length-1)!=="\\"){if(F===J)J=[];if(r.preFilter[z])if(t=r.preFilter[z](t,F,n,J,q,M)){if(t===true)continue}else v=C=true;if(t)for(u=0;(G=F[u])!=null;u++)if(G){C=m(G,t,u,F);y=q^C;if(n&&C!=null)if(y)v=true;else F[u]=false;else if(y){J.push(G);v=true}}if(C!==A){n||(F=J);g=g.replace(r.match[z],"");if(!v)return[];break}}}if(g===w)if(v==null)p.error(g);else break;w=g}return F};p.error=function(g){throw new Error("Syntax error, unrecognized expression: "+
g);};var x=p.getText=function(g){var j,n;j=g.nodeType;var q="";if(j)if(j===1||j===9||j===11)if(typeof g.textContent==="string")return g.textContent;else if(typeof g.innerText==="string")return g.innerText.replace(o,"");else for(g=g.firstChild;g;g=g.nextSibling)q+=x(g);else{if(j===3||j===4)return g.nodeValue}else for(j=0;n=g[j];j++)if(n.nodeType!==8)q+=x(n);return q},r=p.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,
ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")},
type:function(g){return g.getAttribute("type")}},relative:{"+":function(g,j){var n=typeof j==="string",q=n&&!s.test(j);n=n&&!q;if(q)j=j.toLowerCase();q=0;for(var t=g.length,v;q<t;q++)if(v=g[q]){for(;(v=v.previousSibling)&&v.nodeType!==1;);g[q]=n||v&&v.nodeName.toLowerCase()===j?v||false:v===j}n&&p.filter(j,g,true)},">":function(g,j){var n,q=typeof j==="string",t=0,v=g.length;if(q&&!s.test(j))for(j=j.toLowerCase();t<v;t++){if(n=g[t]){n=n.parentNode;g[t]=n.nodeName.toLowerCase()===j?n:false}}else{for(;t<
v;t++)if(n=g[t])g[t]=q?n.parentNode:n.parentNode===j;q&&p.filter(j,g,true)}},"":function(g,j,n){var q,t=f++,v=b;if(typeof j==="string"&&!s.test(j)){q=j=j.toLowerCase();v=a}v("parentNode",j,t,g,q,n)},"~":function(g,j,n){var q,t=f++,v=b;if(typeof j==="string"&&!s.test(j)){q=j=j.toLowerCase();v=a}v("previousSibling",j,t,g,q,n)}},find:{ID:function(g,j,n){if(typeof j.getElementById!=="undefined"&&!n)return(g=j.getElementById(g[1]))&&g.parentNode?[g]:[]},NAME:function(g,j){if(typeof j.getElementsByName!==
"undefined"){var n=[];j=j.getElementsByName(g[1]);for(var q=0,t=j.length;q<t;q++)j[q].getAttribute("name")===g[1]&&n.push(j[q]);return n.length===0?null:n}},TAG:function(g,j){if(typeof j.getElementsByTagName!=="undefined")return j.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,j,n,q,t,v){g=" "+g[1].replace(l,"")+" ";if(v)return g;v=0;for(var z;(z=j[v])!=null;v++)if(z)if(t^(z.className&&(" "+z.className+" ").replace(/[\t\n\r]/g," ").indexOf(g)>=0))n||q.push(z);else if(n)j[v]=false;return false},
ID:function(g){return g[1].replace(l,"")},TAG:function(g){return g[1].replace(l,"").toLowerCase()},CHILD:function(g){if(g[1]==="nth"){g[2]||p.error(g[0]);g[2]=g[2].replace(/^\+|\s*/g,"");var j=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=j[1]+(j[2]||1)-0;g[3]=j[3]-0}else g[2]&&p.error(g[0]);g[0]=f++;return g},ATTR:function(g,j,n,q,t,v){j=g[1]=g[1].replace(l,"");if(!v&&r.attrMap[j])g[1]=r.attrMap[j];g[4]=(g[4]||g[5]||"").replace(l,
"");if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,j,n,q,t){if(g[1]==="not")if((d.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=p(g[3],null,null,j);else{g=p.filter(g[3],j,n,true^t);n||q.push.apply(q,g);return false}else if(r.match.POS.test(g[0])||r.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===
true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},has:function(g,j,n){return!!p(n[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){var j=g.getAttribute("type"),n=g.type;return g.nodeName.toLowerCase()==="input"&&"text"===n&&(j===n||j===null)},radio:function(g){return g.nodeName.toLowerCase()==="input"&&"radio"===g.type},checkbox:function(g){return g.nodeName.toLowerCase()==="input"&&
"checkbox"===g.type},file:function(g){return g.nodeName.toLowerCase()==="input"&&"file"===g.type},password:function(g){return g.nodeName.toLowerCase()==="input"&&"password"===g.type},submit:function(g){var j=g.nodeName.toLowerCase();return(j==="input"||j==="button")&&"submit"===g.type},image:function(g){return g.nodeName.toLowerCase()==="input"&&"image"===g.type},reset:function(g){var j=g.nodeName.toLowerCase();return(j==="input"||j==="button")&&"reset"===g.type},button:function(g){var j=g.nodeName.toLowerCase();
return j==="input"&&"button"===g.type||j==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)},focus:function(g){return g===g.ownerDocument.activeElement}},setFilters:{first:function(g,j){return j===0},last:function(g,j,n,q){return j===q.length-1},even:function(g,j){return j%2===0},odd:function(g,j){return j%2===1},lt:function(g,j,n){return j<n[3]-0},gt:function(g,j,n){return j>n[3]-0},nth:function(g,j,n){return n[3]-0===j},eq:function(g,j,n){return n[3]-0===j}},filter:{PSEUDO:function(g,
j,n,q){var t=j[1],v=r.filters[t];if(v)return v(g,n,j,q);else if(t==="contains")return(g.textContent||g.innerText||x([g])||"").indexOf(j[3])>=0;else if(t==="not"){j=j[3];n=0;for(q=j.length;n<q;n++)if(j[n]===g)return false;return true}else p.error(t)},CHILD:function(g,j){var n,q,t,v;n=j[1];var z=g;switch(n){case "only":case "first":for(;z=z.previousSibling;)if(z.nodeType===1)return false;if(n==="first")return true;z=g;case "last":for(;z=z.nextSibling;)if(z.nodeType===1)return false;return true;case "nth":n=
j[2];q=j[3];if(n===1&&q===0)return true;j=j[0];if((t=g.parentNode)&&(t[e]!==j||!g.nodeIndex)){v=0;for(z=t.firstChild;z;z=z.nextSibling)if(z.nodeType===1)z.nodeIndex=++v;t[e]=j}g=g.nodeIndex-q;return n===0?g===0:g%n===0&&g/n>=0}},ID:function(g,j){return g.nodeType===1&&g.getAttribute("id")===j},TAG:function(g,j){return j==="*"&&g.nodeType===1||!!g.nodeName&&g.nodeName.toLowerCase()===j},CLASS:function(g,j){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(j)>-1},ATTR:function(g,j){var n=
j[1];g=p.attr?p.attr(g,n):r.attrHandle[n]?r.attrHandle[n](g):g[n]!=null?g[n]:g.getAttribute(n);n=g+"";var q=j[2];j=j[4];return g==null?q==="!=":!q&&p.attr?g!=null:q==="="?n===j:q==="*="?n.indexOf(j)>=0:q==="~="?(" "+n+" ").indexOf(j)>=0:!j?n&&g!==false:q==="!="?n!==j:q==="^="?n.indexOf(j)===0:q==="$="?n.substr(n.length-j.length)===j:q==="|="?n===j||n.substr(0,j.length+1)===j+"-":false},POS:function(g,j,n,q){var t=r.setFilters[j[2]];if(t)return t(g,n,j,q)}}},D=r.match.POS,I=function(g,j){return"\\"+
(j-0+1)};for(var K in r.match){r.match[K]=new RegExp(r.match[K].source+/(?![^\[]*\])(?![^\(]*\))/.source);r.leftMatch[K]=new RegExp(/(^(?:.|\r|\n)*?)/.source+r.match[K].source.replace(/\\(\d+)/g,I))}r.match.globalPOS=D;var L=function(g,j){g=Array.prototype.slice.call(g,0);if(j){j.push.apply(j,g);return j}return g};try{Array.prototype.slice.call(B.documentElement.childNodes,0)}catch(S){L=function(g,j){var n=0;j=j||[];if(h.call(g)==="[object Array]")Array.prototype.push.apply(j,g);else if(typeof g.length===
"number")for(var q=g.length;n<q;n++)j.push(g[n]);else for(;g[n];n++)j.push(g[n]);return j}}var E,R;if(B.documentElement.compareDocumentPosition)E=function(g,j){if(g===j){k=true;return 0}if(!g.compareDocumentPosition||!j.compareDocumentPosition)return g.compareDocumentPosition?-1:1;return g.compareDocumentPosition(j)&4?-1:1};else{E=function(g,j){if(g===j){k=true;return 0}else if(g.sourceIndex&&j.sourceIndex)return g.sourceIndex-j.sourceIndex;var n,q,t=[],v=[];n=g.parentNode;q=j.parentNode;var z=n;
if(n===q)return R(g,j);else if(n){if(!q)return 1}else return-1;for(;z;){t.unshift(z);z=z.parentNode}for(z=q;z;){v.unshift(z);z=z.parentNode}n=t.length;q=v.length;for(z=0;z<n&&z<q;z++)if(t[z]!==v[z])return R(t[z],v[z]);return z===n?R(g,v[z],-1):R(t[z],j,1)};R=function(g,j,n){if(g===j)return n;for(g=g.nextSibling;g;){if(g===j)return-1;g=g.nextSibling}return 1}}(function(){var g=B.createElement("div"),j="script"+(new Date).getTime(),n=B.documentElement;g.innerHTML="<a name='"+j+"'/>";n.insertBefore(g,
n.firstChild);if(B.getElementById(j)){r.find.ID=function(q,t,v){if(typeof t.getElementById!=="undefined"&&!v)return(t=t.getElementById(q[1]))?t.id===q[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===q[1]?[t]:A:[]};r.filter.ID=function(q,t){var v=typeof q.getAttributeNode!=="undefined"&&q.getAttributeNode("id");return q.nodeType===1&&v&&v.nodeValue===t}}n.removeChild(g);n=g=null})();(function(){var g=B.createElement("div");g.appendChild(B.createComment(""));if(g.getElementsByTagName("*").length>
0)r.find.TAG=function(j,n){n=n.getElementsByTagName(j[1]);if(j[1]==="*"){j=[];for(var q=0;n[q];q++)n[q].nodeType===1&&j.push(n[q]);n=j}return n};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")r.attrHandle.href=function(j){return j.getAttribute("href",2)};g=null})();B.querySelectorAll&&function(){var g=p,j=B.createElement("div");j.innerHTML="<p class='TEST'></p>";if(!(j.querySelectorAll&&j.querySelectorAll(".TEST").length===
0)){p=function(q,t,v,z){t=t||B;if(!z&&!p.isXML(t)){var C=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(q);if(C&&(t.nodeType===1||t.nodeType===9))if(C[1])return L(t.getElementsByTagName(q),v);else if(C[2]&&r.find.CLASS&&t.getElementsByClassName)return L(t.getElementsByClassName(C[2]),v);if(t.nodeType===9){if(q==="body"&&t.body)return L([t.body],v);else if(C&&C[3]){var G=t.getElementById(C[3]);if(G&&G.parentNode){if(G.id===C[3])return L([G],v)}else return L([],v)}try{return L(t.querySelectorAll(q),v)}catch(m){}}else if(t.nodeType===
1&&t.nodeName.toLowerCase()!=="object"){C=t;var u=(G=t.getAttribute("id"))||"__sizzle__",y=t.parentNode,w=/^\s*[+~]/.test(q);if(G)u=u.replace(/'/g,"\\$&");else t.setAttribute("id",u);if(w&&y)t=t.parentNode;try{if(!w||y)return L(t.querySelectorAll("[id='"+u+"'] "+q),v)}catch(J){}finally{G||C.removeAttribute("id")}}}return g(q,t,v,z)};for(var n in g)p[n]=g[n];j=null}}();(function(){var g=B.documentElement,j=g.matchesSelector||g.mozMatchesSelector||g.webkitMatchesSelector||g.msMatchesSelector;if(j){var n=
!j.call(B.createElement("div"),"div"),q=false;try{j.call(B.documentElement,"[test!='']:sizzle")}catch(t){q=true}p.matchesSelector=function(v,z){z=z.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!p.isXML(v))try{if(q||!r.match.PSEUDO.test(z)&&!/!=/.test(z)){var C=j.call(v,z);if(C||!n||v.document&&v.document.nodeType!==11)return C}}catch(G){}return p(z,null,null,[v]).length>0}}})();(function(){var g=B.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||
g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){r.order.splice(1,0,"CLASS");r.find.CLASS=function(j,n,q){if(typeof n.getElementsByClassName!=="undefined"&&!q)return n.getElementsByClassName(j[1])};g=null}}})();p.contains=B.documentElement.contains?function(g,j){return g!==j&&(g.contains?g.contains(j):true)}:B.documentElement.compareDocumentPosition?function(g,j){return!!(g.compareDocumentPosition(j)&16)}:function(){return false};p.isXML=
function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false};var P=function(g,j,n){var q,t=[],v="";for(j=j.nodeType?[j]:j;q=r.match.PSEUDO.exec(g);){v+=q[0];g=g.replace(r.match.PSEUDO,"")}g=r.relative[g]?g+"*":g;q=0;for(var z=j.length;q<z;q++)p(g,j[q],t,n);return p.filter(v,t)};p.attr=c.attr;p.selectors.attrMap={};c.find=p;c.expr=p.selectors;c.expr[":"]=c.expr.filters;c.unique=p.uniqueSort;c.text=p.getText;c.isXMLDoc=p.isXML;c.contains=p.contains})();var Mb=/Until$/,Nb=
/^(?:parents|prevUntil|prevAll)/,Ob=/,/,qb=/^.[^:#\[\.,]*$/,Pb=Array.prototype.slice,Ya=c.expr.match.globalPOS,Qb={children:true,contents:true,next:true,prev:true};c.fn.extend({find:function(a){var b=this,d,e;if(typeof a!=="string")return c(a).filter(function(){d=0;for(e=b.length;d<e;d++)if(c.contains(b[d],this))return true});var f=this.pushStack("","find",a),h,k,i;d=0;for(e=this.length;d<e;d++){h=f.length;c.find(a,this[d],f);if(d>0)for(k=h;k<f.length;k++)for(i=0;i<h;i++)if(f[i]===f[k]){f.splice(k--,
1);break}}return f},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Aa(this,a,false),"not",a)},filter:function(a){return this.pushStack(Aa(this,a,true),"filter",a)},is:function(a){return!!a&&(typeof a==="string"?Ya.test(a)?c(a,this.context).index(this[0])>=0:c.filter(a,this).length>0:this.filter(a).length>0)},closest:function(a,b){var d=[],e,f,h=this[0];if(c.isArray(a)){for(f=1;h&&
h.ownerDocument&&h!==b;){for(e=0;e<a.length;e++)c(h).is(a[e])&&d.push({selector:a[e],elem:h,level:f});h=h.parentNode;f++}return d}var k=Ya.test(a)||typeof a!=="string"?c(a,b||this.context):0;e=0;for(f=this.length;e<f;e++)for(h=this[e];h;)if(k?k.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===b||h.nodeType===11)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",a)},index:function(a){if(!a)return this[0]&&this[0].parentNode?this.prevAll().length:
-1;if(typeof a==="string")return c.inArray(this[0],c(a));return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b):c.makeArray(a&&a.nodeType?[a]:a);b=c.merge(this.get(),a);return this.pushStack(za(a[0])||za(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,
2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:
c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);Mb.test(a)||(e=d);if(e&&typeof e==="string")f=c.filter(e,f);f=this.length>1&&!Qb[a]?c.unique(f):f;if((this.length>1||Ob.test(e))&&Nb.test(a))f=f.reverse();return this.pushStack(f,a,Pb.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=[];for(a=a[b];a&&a.nodeType!==9&&(d===A||
a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Ca="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",Rb=/ jQuery\d+="(?:\d+|null)"/g,ta=/^\s+/,Za=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,
$a=/<([\w:]+)/,Sb=/<tbody/i,Tb=/<|&#?\w+;/,Ub=/<(?:script|style)/i,Vb=/<(?:script|object|embed|option|style)/i,ab=new RegExp("<(?:"+Ca+")[\\s/>]","i"),bb=/checked\s*(?:[^=]|=\s*.checked.)/i,cb=/\/(java|ecma)script/i,Wb=/^\s*<!(?:\[CDATA\[|\-\-)/,O={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>",
"</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]},ma=Ba(B);O.optgroup=O.option;O.tbody=O.tfoot=O.colgroup=O.caption=O.thead;O.th=O.td;if(!c.support.htmlSerialize)O._default=[1,"div<div>","</div>"];c.fn.extend({text:function(a){return c.access(this,function(b){return b===A?c.text(this):this.empty().append((this[0]&&this[0].ownerDocument||B).createTextNode(b))},null,a,arguments.length)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,
d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?
a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,
this)});else if(arguments.length){var a=c.clean(arguments);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c.clean(arguments));return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===
1){c.cleanData(e.getElementsByTagName("*"));c.cleanData([e])}e.parentNode&&e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},clone:function(a,b){a=a==null?false:a;b=b==null?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(b){var d=this[0]||{},e=0,f=this.length;if(b===A)return d.nodeType===
1?d.innerHTML.replace(Rb,""):null;if(typeof b==="string"&&!Ub.test(b)&&(c.support.leadingWhitespace||!ta.test(b))&&!O[($a.exec(b)||["",""])[1].toLowerCase()]){b=b.replace(Za,"<$1></$2>");try{for(;e<f;e++){d=this[e]||{};if(d.nodeType===1){c.cleanData(d.getElementsByTagName("*"));d.innerHTML=b}}d=0}catch(h){}}d&&this.empty().append(b)},null,a,arguments.length)},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,
b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.length?this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){var e,f,h,k=a[0],i=[];if(!c.support.checkClone&&arguments.length===3&&typeof k==="string"&&bb.test(k))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(k))return this.each(function(p){var x=
c(this);a[0]=k.call(this,p,b?x.html():A);x.domManip(a,b,d)});if(this[0]){e=k&&k.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,i);h=e.fragment;if(f=h.childNodes.length===1?(h=h.firstChild):h.firstChild){b=b&&c.nodeName(f,"tr");for(var l=0,o=this.length,s=o-1;l<o;l++)d.call(b?rb(this[l],f):this[l],e.cacheable||o>1&&l<s?c.clone(h,true,true):h)}i.length&&c.each(i,function(p,x){x.src?c.ajax({type:"GET",global:false,url:x.src,
async:false,dataType:"script"}):c.globalEval((x.text||x.textContent||x.innerHTML||"").replace(Wb,"/*$0*/"));x.parentNode&&x.parentNode.removeChild(x)})}return this}});c.buildFragment=function(a,b,d){var e,f,h,k,i=a[0];if(b&&b[0])k=b[0].ownerDocument||b[0];k.createDocumentFragment||(k=B);if(a.length===1&&typeof i==="string"&&i.length<512&&k===B&&i.charAt(0)==="<"&&!Vb.test(i)&&(c.support.checkClone||!bb.test(i))&&(c.support.html5Clone||!ab.test(i))){f=true;if((h=c.fragments[i])&&h!==1)e=h}if(!e){e=
k.createDocumentFragment();c.clean(a,k,e,d)}if(f)c.fragments[i]=h?e:1;return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{f=0;for(var h=d.length;f<h;f++){var k=(f>0?this.clone(true):this).get();c(d[f])[b](k);
e=e.concat(k)}return this.pushStack(e,a,d.selector)}}});c.extend({clone:function(a,b,d){var e,f,h,k=c.support.html5Clone||c.isXMLDoc(a)||!ab.test("<"+a.nodeName+">")?a.cloneNode(true):sb(a);if((!c.support.noCloneEvent||!c.support.noCloneChecked)&&(a.nodeType===1||a.nodeType===11)&&!c.isXMLDoc(a)){Ea(a,k);e=ea(a);f=ea(k);for(h=0;e[h];++h)f[h]&&Ea(e[h],f[h])}if(b){Da(a,k);if(d){e=ea(a);f=ea(k);for(h=0;e[h];++h)Da(e[h],f[h])}}return k},clean:function(a,b,d,e){var f,h=[];b=b||B;if(typeof b.createElement===
"undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||B;for(var k=0,i;(i=a[k])!=null;k++){if(typeof i==="number")i+="";if(i){if(typeof i==="string")if(Tb.test(i)){i=i.replace(Za,"<$1></$2>");f=($a.exec(i)||["",""])[1].toLowerCase();var l=O[f]||O._default,o=l[0],s=b.createElement("div"),p=ma.childNodes;b===B?ma.appendChild(s):Ba(b).appendChild(s);for(s.innerHTML=l[1]+i+l[2];o--;)s=s.lastChild;if(!c.support.tbody){o=Sb.test(i);l=f==="table"&&!o?s.firstChild&&s.firstChild.childNodes:l[1]==="<table>"&&
!o?s.childNodes:[];for(f=l.length-1;f>=0;--f)c.nodeName(l[f],"tbody")&&!l[f].childNodes.length&&l[f].parentNode.removeChild(l[f])}!c.support.leadingWhitespace&&ta.test(i)&&s.insertBefore(b.createTextNode(ta.exec(i)[0]),s.firstChild);i=s.childNodes;if(s){s.parentNode.removeChild(s);if(p.length>0)(s=p[p.length-1])&&s.parentNode&&s.parentNode.removeChild(s)}}else i=b.createTextNode(i);var x;if(!c.support.appendChecked)if(i[0]&&typeof(x=i.length)==="number")for(f=0;f<x;f++)Ga(i[f]);else Ga(i);if(i.nodeType)h.push(i);
else h=c.merge(h,i)}}if(d){a=function(r){return!r.type||cb.test(r.type)};for(k=0;h[k];k++){b=h[k];if(e&&c.nodeName(b,"script")&&(!b.type||cb.test(b.type)))e.push(b.parentNode?b.parentNode.removeChild(b):b);else{if(b.nodeType===1){i=c.grep(b.getElementsByTagName("script"),a);h.splice.apply(h,[k+1,0].concat(i))}d.appendChild(b)}}}return h},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,h=c.support.deleteExpando,k=0,i;(i=a[k])!=null;k++)if(!(i.nodeName&&c.noData[i.nodeName.toLowerCase()]))if(d=
i[c.expando]){if((b=e[d])&&b.events){for(var l in b.events)f[l]?c.event.remove(i,l):c.removeEvent(i,l,b.handle);if(b.handle)b.handle.elem=null}if(h)delete i[c.expando];else i.removeAttribute&&i.removeAttribute(c.expando);delete e[d]}}});var ua=/alpha\([^)]*\)/i,Xb=/opacity=([^)]*)/,Yb=/([A-Z]|^ms)/g,Zb=/^[\-+]?(?:\d*\.)?\d+$/i,na=/^-?(?:\d*\.)?\d+(?!px)[^\d\s]+$/i,$b=/^([\-+])=([\-+.\de]+)/,ac=/^margin/,bc={position:"absolute",visibility:"hidden",display:"block"},V=["Top","Right","Bottom","Left"],
Z,db,eb;c.fn.css=function(a,b){return c.access(this,function(d,e,f){return f!==A?c.style(d,e,f):c.css(d,e)},a,b,arguments.length>1)};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){a=Z(a,"opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{fillOpacity:true,fontWeight:true,lineHeight:true,opacity:true,orphans:true,widows:true,zIndex:true,zoom:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||
!a.style)){var f,h=c.camelCase(b),k=a.style,i=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==A){e=typeof d;if(e==="string"&&(f=$b.exec(d))){d=+(f[1]+1)*+f[2]+parseFloat(c.css(a,b));e="number"}if(!(d==null||e==="number"&&isNaN(d))){if(e==="number"&&!c.cssNumber[h])d+="px";if(!i||!("set"in i)||(d=i.set(a,d))!==A)try{k[b]=d}catch(l){}}}else{if(i&&"get"in i&&(f=i.get(a,false,e))!==A)return f;return k[b]}}},css:function(a,b,d){var e,f;b=c.camelCase(b);f=c.cssHooks[b];b=c.cssProps[b]||b;if(b==="cssFloat")b="float";
if(f&&"get"in f&&(e=f.get(a,true,d))!==A)return e;else if(Z)return Z(a,b)},swap:function(a,b,d){var e={},f;for(f in b){e[f]=a.style[f];a.style[f]=b[f]}d=d.call(a);for(f in b)a.style[f]=e[f];return d}});c.curCSS=c.css;if(B.defaultView&&B.defaultView.getComputedStyle)db=function(a,b){var d,e,f,h=a.style;b=b.replace(Yb,"-$1").toLowerCase();if((e=a.ownerDocument.defaultView)&&(f=e.getComputedStyle(a,null))){d=f.getPropertyValue(b);if(d===""&&!c.contains(a.ownerDocument.documentElement,a))d=c.style(a,
b)}if(!c.support.pixelMargin&&f&&ac.test(b)&&na.test(d)){a=h.width;h.width=d;d=f.width;h.width=a}return d};if(B.documentElement.currentStyle)eb=function(a,b){var d,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;if(f==null&&h&&(d=h[b]))f=d;if(na.test(f)){d=h.left;if(e=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;h.left=b==="fontSize"?"1em":f;f=h.pixelLeft+"px";h.left=d;if(e)a.runtimeStyle.left=e}return f===""?"auto":f};Z=db||eb;c.each(["height","width"],function(a,b){c.cssHooks[b]=
{get:function(d,e,f){if(e)return d.offsetWidth!==0?Ha(d,b,f):c.swap(d,bc,function(){return Ha(d,b,f)})},set:function(d,e){return Zb.test(e)?e+"px":e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return Xb.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var d=a.style;a=a.currentStyle;var e=c.isNumeric(b)?"alpha(opacity="+b*100+")":"",f=a&&a.filter||d.filter||"";d.zoom=1;if(b>=1&&c.trim(f.replace(ua,""))===
""){d.removeAttribute("filter");if(a&&!a.filter)return}d.filter=ua.test(f)?f.replace(ua,e):f+" "+e}};c(function(){if(!c.support.reliableMarginRight)c.cssHooks.marginRight={get:function(a,b){return c.swap(a,{display:"inline-block"},function(){return b?Z(a,"margin-right"):a.style.marginRight})}}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style&&a.style.display||c.css(a,"display"))==="none"};
c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(d){var e=typeof d==="string"?d.split(" "):[d],f={};for(d=0;d<4;d++)f[a+V[d]+b]=e[d]||e[d-2]||e[0];return f}}});var cc=/%20/g,tb=/\[\]$/,fb=/\r?\n/g,dc=/#.*$/,ec=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,fc=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,gc=/^(?:GET|HEAD)$/,hc=/^\/\//,
gb=/\?/,ic=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,jc=/^(?:select|textarea)/i,Ja=/\s+/,kc=/([?&])_=[^&]*/,hb=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,ib=c.fn.load,oa={},jb={},W,X,kb=["*/"]+["*"];try{W=zb.href}catch(rc){W=B.createElement("a");W.href="";W=W.href}X=hb.exec(W.toLowerCase())||[];c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&ib)return ib.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var f=a.slice(e,a.length);a=a.slice(0,
e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=A}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",data:b,complete:function(k,i,l){l=k.responseText;if(k.isResolved()){k.done(function(o){l=o});h.html(f?c("<div>").append(l.replace(ic,"")).find(f):l)}d&&h.each(d,[l,i,k])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):
this}).filter(function(){return this.name&&!this.disabled&&(this.checked||jc.test(this.nodeName)||fc.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d.replace(fb,"\r\n")}}):{name:b.name,value:a.replace(fb,"\r\n")}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.on(b,d)}});c.each(["get","post"],function(a,b){c[b]=function(d,e,
f,h){if(c.isFunction(e)){h=h||f;f=e;e=A}return c.ajax({type:b,url:d,data:e,success:f,dataType:h})}});c.extend({getScript:function(a,b){return c.get(a,A,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},ajaxSetup:function(a,b){if(b)Ka(a,c.ajaxSettings);else{b=a;a=c.ajaxSettings}Ka(a,b);return a},ajaxSettings:{url:W,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(X[1]),global:true,type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",processData:true,
async:true,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":kb},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":H.String,"text html":true,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{context:true,url:true}},ajaxPrefilter:Ia(oa),ajaxTransport:Ia(jb),ajax:function(a,b){function d(g,j,n,q){if(K!==2){K=2;I&&clearTimeout(I);D=A;x=q||"";E.readyState=
g>0?4:0;var t,v,z;q=j;n=n?ub(e,E,n):A;var C;if(g>=200&&g<300||g===304){if(e.ifModified){if(C=E.getResponseHeader("Last-Modified"))c.lastModified[o]=C;if(C=E.getResponseHeader("Etag"))c.etag[o]=C}if(g===304){q="notmodified";t=true}else try{v=vb(e,n);q="success";t=true}catch(G){q="parsererror";z=G}}else{z=q;if(!q||g){q="error";if(g<0)g=0}}E.status=g;E.statusText=""+(j||q);t?k.resolveWith(f,[v,q,E]):k.rejectWith(f,[E,q,z]);E.statusCode(l);l=A;if(L)h.trigger("ajax"+(t?"Success":"Error"),[E,e,t?v:z]);
i.fireWith(f,[E,q]);if(L){h.trigger("ajaxComplete",[E,e]);--c.active||c.event.trigger("ajaxStop")}}}if(typeof a==="object"){b=a;a=A}b=b||{};var e=c.ajaxSetup({},b),f=e.context||e,h=f!==e&&(f.nodeType||f instanceof c)?c(f):c.event,k=c.Deferred(),i=c.Callbacks("once memory"),l=e.statusCode||{},o,s={},p={},x,r,D,I,K=0,L,S,E={readyState:0,setRequestHeader:function(g,j){if(!K){var n=g.toLowerCase();g=p[n]=p[n]||g;s[g]=j}return this},getAllResponseHeaders:function(){return K===2?x:null},getResponseHeader:function(g){var j;
if(K===2){if(!r)for(r={};j=ec.exec(x);)r[j[1].toLowerCase()]=j[2];j=r[g.toLowerCase()]}return j===A?null:j},overrideMimeType:function(g){if(!K)e.mimeType=g;return this},abort:function(g){g=g||"abort";D&&D.abort(g);d(0,g);return this}};k.promise(E);E.success=E.done;E.error=E.fail;E.complete=i.add;E.statusCode=function(g){if(g){var j;if(K<2)for(j in g)l[j]=[l[j],g[j]];else{j=g[E.status];E.then(j,j)}}return this};e.url=((a||e.url)+"").replace(dc,"").replace(hc,X[1]+"//");e.dataTypes=c.trim(e.dataType||
"*").toLowerCase().split(Ja);if(e.crossDomain==null){a=hb.exec(e.url.toLowerCase());e.crossDomain=!!(a&&(a[1]!=X[1]||a[2]!=X[2]||(a[3]||(a[1]==="http:"?80:443))!=(X[3]||(X[1]==="http:"?80:443))))}if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);fa(oa,e,b,E);if(K===2)return false;L=e.global;e.type=e.type.toUpperCase();e.hasContent=!gc.test(e.type);L&&c.active++===0&&c.event.trigger("ajaxStart");if(!e.hasContent){if(e.data){e.url+=(gb.test(e.url)?"&":"?")+e.data;
delete e.data}o=e.url;if(e.cache===false){a=c.now();var R=e.url.replace(kc,"$1_="+a);e.url=R+(R===e.url?(gb.test(e.url)?"&":"?")+"_="+a:"")}}if(e.data&&e.hasContent&&e.contentType!==false||b.contentType)E.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){o=o||e.url;c.lastModified[o]&&E.setRequestHeader("If-Modified-Since",c.lastModified[o]);c.etag[o]&&E.setRequestHeader("If-None-Match",c.etag[o])}E.setRequestHeader("Accept",e.dataTypes[0]&&e.accepts[e.dataTypes[0]]?e.accepts[e.dataTypes[0]]+
(e.dataTypes[0]!=="*"?", "+kb+"; q=0.01":""):e.accepts["*"]);for(S in e.headers)E.setRequestHeader(S,e.headers[S]);if(e.beforeSend&&(e.beforeSend.call(f,E,e)===false||K===2)){E.abort();return false}for(S in{success:1,error:1,complete:1})E[S](e[S]);if(D=fa(jb,e,b,E)){E.readyState=1;L&&h.trigger("ajaxSend",[E,e]);if(e.async&&e.timeout>0)I=setTimeout(function(){E.abort("timeout")},e.timeout);try{K=1;D.send(s,d)}catch(P){if(K<2)d(-1,P);else throw P;}}else d(-1,"No Transport");return E},param:function(a,
b){var d=[],e=function(h,k){k=c.isFunction(k)?k():k;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(k)};if(b===A)b=c.ajaxSettings.traditional;if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){e(this.name,this.value)});else for(var f in a)pa(f,a[f],b,e);return d.join("&").replace(cc,"+")}});c.extend({active:0,lastModified:{},etag:{}});var lc=c.now(),ja=/(\=)\?(&|$)|\?\?/i;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){return c.expando+"_"+lc++}});c.ajaxPrefilter("json jsonp",
function(a,b,d){b=typeof a.data==="string"&&/^application\/x\-www\-form\-urlencoded/.test(a.contentType);if(a.dataTypes[0]==="jsonp"||a.jsonp!==false&&(ja.test(a.url)||b&&ja.test(a.data))){var e,f=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h=H[f],k=a.url,i=a.data,l="$1"+f+"$2";if(a.jsonp!==false){k=k.replace(ja,l);if(a.url===k){if(b)i=i.replace(ja,l);if(a.data===i)k+=(/\?/.test(k)?"&":"?")+a.jsonp+"="+f}}a.url=k;a.data=i;H[f]=function(o){e=[o]};d.always(function(){H[f]=
h;e&&c.isFunction(h)&&H[f](e[0])});a.converters["script json"]=function(){e||c.error(f+" was not called");return e[0]};a.dataTypes[0]="json";return"script"}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){if(a.cache===A)a.cache=false;if(a.crossDomain){a.type="GET";a.global=false}});
c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d=B.head||B.getElementsByTagName("head")[0]||B.documentElement;return{send:function(e,f){b=B.createElement("script");b.async="async";if(a.scriptCharset)b.charset=a.scriptCharset;b.src=a.url;b.onload=b.onreadystatechange=function(h,k){if(k||!b.readyState||/loaded|complete/.test(b.readyState)){b.onload=b.onreadystatechange=null;d&&b.parentNode&&d.removeChild(b);b=A;k||f(200,"success")}};d.insertBefore(b,d.firstChild)},abort:function(){b&&
b.onload(0,1)}}}});var va=H.ActiveXObject?function(){for(var a in ca)ca[a](0,1)}:false,mc=0,ca;c.ajaxSettings.xhr=H.ActiveXObject?function(){return!this.isLocal&&La()||wb()}:La;(function(a){c.extend(c.support,{ajax:!!a,cors:!!a&&"withCredentials"in a})})(c.ajaxSettings.xhr());c.support.ajax&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f=a.xhr(),h,k;a.username?f.open(a.type,a.url,a.async,a.username,a.password):f.open(a.type,a.url,a.async);if(a.xhrFields)for(k in a.xhrFields)f[k]=
a.xhrFields[k];a.mimeType&&f.overrideMimeType&&f.overrideMimeType(a.mimeType);if(!a.crossDomain&&!d["X-Requested-With"])d["X-Requested-With"]="XMLHttpRequest";try{for(k in d)f.setRequestHeader(k,d[k])}catch(i){}f.send(a.hasContent&&a.data||null);b=function(l,o){var s,p,x,r,D;try{if(b&&(o||f.readyState===4)){b=A;if(h){f.onreadystatechange=c.noop;va&&delete ca[h]}if(o)f.readyState!==4&&f.abort();else{s=f.status;x=f.getAllResponseHeaders();r={};if((D=f.responseXML)&&D.documentElement)r.xml=D;try{r.text=
f.responseText}catch(I){}try{p=f.statusText}catch(K){p=""}if(!s&&a.isLocal&&!a.crossDomain)s=r.text?200:404;else if(s===1223)s=204}}}catch(L){o||e(-1,L)}r&&e(s,p,r,x)};if(!a.async||f.readyState===4)b();else{h=++mc;if(va){if(!ca){ca={};c(H).unload(va)}ca[h]=b}f.onreadystatechange=b}},abort:function(){b&&b(0,1)}}}});var qa={},Q,aa,nc=/^(?:toggle|show|hide)$/,oc=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,ka,ha=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight",
"paddingLeft","paddingRight"],["opacity"]],ga;c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate($("show",3),a,b,d);else{d=0;for(var e=this.length;d<e;d++){a=this[d];if(a.style){b=a.style.display;if(!c._data(a,"olddisplay")&&b==="none")b=a.style.display="";if(b===""&&c.css(a,"display")==="none"||!c.contains(a.ownerDocument.documentElement,a))c._data(a,"olddisplay",Na(a.nodeName))}}for(d=0;d<e;d++){a=this[d];if(a.style){b=a.style.display;if(b===""||b==="none")a.style.display=c._data(a,
"olddisplay")||""}}return this}},hide:function(a,b,d){if(a||a===0)return this.animate($("hide",3),a,b,d);else{d=0;for(var e=this.length;d<e;d++){a=this[d];if(a.style){b=c.css(a,"display");b!=="none"&&!c._data(a,"olddisplay")&&c._data(a,"olddisplay",b)}}for(d=0;d<e;d++)if(this[d].style)this[d].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||e?this.each(function(){var f=
e?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate($("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){function f(){h.queue===false&&c._mark(this);var k=c.extend({},h),i=this.nodeType===1,l=i&&c(this).is(":hidden"),o,s,p,x,r;k.animatedProperties={};for(p in a){o=c.camelCase(p);if(p!==o){a[o]=a[p];delete a[p]}if((s=c.cssHooks[o])&&"expand"in s){x=s.expand(a[o]);
delete a[o];for(p in x)p in a||(a[p]=x[p])}}for(o in a){s=a[o];if(c.isArray(s)){k.animatedProperties[o]=s[1];s=a[o]=s[0]}else k.animatedProperties[o]=k.specialEasing&&k.specialEasing[o]||k.easing||"swing";if(s==="hide"&&l||s==="show"&&!l)return k.complete.call(this);if(i&&(o==="height"||o==="width")){k.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(!c.support.inlineBlockNeedsLayout||Na(this.nodeName)===
"inline")this.style.display="inline-block";else this.style.zoom=1}}if(k.overflow!=null)this.style.overflow="hidden";for(p in a){i=new c.fx(this,k,p);s=a[p];if(nc.test(s))if(o=c._data(this,"toggle"+p)||(s==="toggle"?l?"show":"hide":0)){c._data(this,"toggle"+p,o==="show"?"hide":"show");i[o]()}else i[s]();else{o=oc.exec(s);x=i.cur();if(o){s=parseFloat(o[2]);r=o[3]||(c.cssNumber[p]?"":"px");if(r!=="px"){c.style(this,p,(s||1)+r);x=(s||1)/i.cur()*x;c.style(this,p,x+r)}if(o[1])s=(o[1]==="-="?-1:1)*s+x;i.custom(x,
s,r)}else i.custom(x,s,"")}}return true}var h=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(h.complete,[false]);a=c.extend({},a);return h.queue===false?this.each(f):this.queue(h.queue,f)},stop:function(a,b,d){if(typeof a!=="string"){d=b;b=a;a=A}if(b&&a!==false)this.queue(a||"fx",[]);return this.each(function(){function e(l,o,s){o=o[s];c.removeData(l,s,true);o.stop(d)}var f,h=false,k=c.timers,i=c._data(this);d||c._unmark(true,this);if(a==null)for(f in i)i[f]&&i[f].stop&&f.indexOf(".run")===
f.length-4&&e(this,i,f);else if(i[f=a+".run"]&&i[f].stop)e(this,i,f);for(f=k.length;f--;)if(k[f].elem===this&&(a==null||k[f].queue===a)){d?k[f](true):k[f].saveState();h=true;k.splice(f,1)}d&&h||c.dequeue(this,a)})}});c.each({slideDown:$("show",1),slideUp:$("hide",1),slideToggle:$("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(d,e,f){return this.animate(b,d,e,f)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?
c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(e.queue==null||e.queue===true)e.queue="fx";e.old=e.complete;e.complete=function(f){c.isFunction(e.old)&&e.old.call(this);if(e.queue)c.dequeue(this,e.queue);else f!==false&&c._unmark(this)};return e},easing:{linear:function(a){return a},swing:function(a){return-Math.cos(a*
Math.PI)/2+0.5}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;b.orig=b.orig||{}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a,b=c.css(this.elem,this.prop);return isNaN(a=parseFloat(b))?!b||b==="auto"?0:b:a},custom:function(a,b,d){function e(k){return f.step(k)}
var f=this,h=c.fx;this.startTime=ga||Ma();this.end=b;this.now=this.start=a;this.pos=this.state=0;this.unit=d||this.unit||(c.cssNumber[this.prop]?"":"px");e.queue=this.options.queue;e.elem=this.elem;e.saveState=function(){if(c._data(f.elem,"fxshow"+f.prop)===A)if(f.options.hide)c._data(f.elem,"fxshow"+f.prop,f.start);else f.options.show&&c._data(f.elem,"fxshow"+f.prop,f.end)};if(e()&&c.timers.push(e)&&!ka)ka=setInterval(h.tick,h.interval)},show:function(){var a=c._data(this.elem,"fxshow"+this.prop);
this.options.orig[this.prop]=a||c.style(this.elem,this.prop);this.options.show=true;a!==A?this.custom(this.cur(),a):this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c._data(this.elem,"fxshow"+this.prop)||c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b,d=ga||Ma(),e=true,f=this.elem,h=this.options;if(a||d>=h.duration+this.startTime){this.now=this.end;this.pos=
this.state=1;this.update();h.animatedProperties[this.prop]=true;for(b in h.animatedProperties)if(h.animatedProperties[b]!==true)e=false;if(e){h.overflow!=null&&!c.support.shrinkWrapBlocks&&c.each(["","X","Y"],function(k,i){f.style["overflow"+i]=h.overflow[k]});h.hide&&c(f).hide();if(h.hide||h.show)for(b in h.animatedProperties){c.style(f,b,h.orig[b]);c.removeData(f,"fxshow"+b,true);c.removeData(f,"toggle"+b,true)}if(a=h.complete){h.complete=false;a.call(f)}}return false}else{if(h.duration==Infinity)this.now=
d;else{a=d-this.startTime;this.state=a/h.duration;this.pos=c.easing[h.animatedProperties[this.prop]](this.state,a,0,1,h.duration);this.now=this.start+(this.end-this.start)*this.pos}this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a,b=c.timers,d=0;d<b.length;d++){a=b[d];!a()&&b[d]===a&&b.splice(d--,1)}b.length||c.fx.stop()},interval:13,stop:function(){clearInterval(ka);ka=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&
a.elem.style[a.prop]!=null)a.elem.style[a.prop]=a.now+a.unit;else a.elem[a.prop]=a.now}}});c.each(ha.concat.apply([],ha),function(a,b){if(b.indexOf("margin"))c.fx.step[b]=function(d){c.style(d.elem,b,Math.max(0,d.now)+d.unit)}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var lb,pc=/^t(?:able|d|h)$/i,mb=/^(?:body|html)$/i;lb="getBoundingClientRect"in B.documentElement?function(a,b,d,e){try{e=a.getBoundingClientRect()}catch(f){}if(!e||
!c.contains(d,a))return e?{top:e.top,left:e.left}:{top:0,left:0};a=b.body;b=Oa(b);return{top:e.top+(b.pageYOffset||c.support.boxModel&&d.scrollTop||a.scrollTop)-(d.clientTop||a.clientTop||0),left:e.left+(b.pageXOffset||c.support.boxModel&&d.scrollLeft||a.scrollLeft)-(d.clientLeft||a.clientLeft||0)}}:function(a,b,d){var e,f=a.offsetParent,h=b.body;e=(b=b.defaultView)?b.getComputedStyle(a,null):a.currentStyle;for(var k=a.offsetTop,i=a.offsetLeft;(a=a.parentNode)&&a!==h&&a!==d;){if(c.support.fixedPosition&&
e.position==="fixed")break;e=b?b.getComputedStyle(a,null):a.currentStyle;k-=a.scrollTop;i-=a.scrollLeft;if(a===f){k+=a.offsetTop;i+=a.offsetLeft;if(c.support.doesNotAddBorder&&!(c.support.doesAddBorderForTableAndCells&&pc.test(a.nodeName))){k+=parseFloat(e.borderTopWidth)||0;i+=parseFloat(e.borderLeftWidth)||0}f=a.offsetParent}if(c.support.subtractsBorderForOverflowNotVisible&&e.overflow!=="visible"){k+=parseFloat(e.borderTopWidth)||0;i+=parseFloat(e.borderLeftWidth)||0}e=e}if(e.position==="relative"||
e.position==="static"){k+=h.offsetTop;i+=h.offsetLeft}if(c.support.fixedPosition&&e.position==="fixed"){k+=Math.max(d.scrollTop,h.scrollTop);i+=Math.max(d.scrollLeft,h.scrollLeft)}return{top:k,left:i}};c.fn.offset=function(a){if(arguments.length)return a===A?this:this.each(function(e){c.offset.setOffset(this,a,e)});var b=this[0],d=b&&b.ownerDocument;if(!d)return null;if(b===d.body)return c.offset.bodyOffset(b);return lb(b,d,d.documentElement)};c.offset={bodyOffset:function(a){var b=a.offsetTop,d=
a.offsetLeft;if(c.support.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),h=f.offset(),k=c.css(a,"top"),i=c.css(a,"left"),l={},o={};if((e==="absolute"||e==="fixed")&&c.inArray("auto",[k,i])>-1){o=f.position();e=o.top;i=o.left}else{e=parseFloat(k)||0;i=parseFloat(i)||0}if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=
null)l.top=b.top-h.top+e;if(b.left!=null)l.left=b.left-h.left+i;"using"in b?b.using.call(a,l):f.css(l)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=mb.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},
offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||B.body;a&&!mb.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(f,h,k){var i=Oa(f);if(k===A)return i?b in i?i[b]:c.support.boxModel&&i.document.documentElement[h]||i.document.body[h]:f[h];if(i)i.scrollTo(!d?k:c(i).scrollLeft(),d?k:c(i).scrollTop());else f[h]=
k},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){var d="client"+a,e="scroll"+a,f="offset"+a;c.fn["inner"+a]=function(){var h=this[0];return h?h.style?parseFloat(c.css(h,b,"padding")):this[b]():null};c.fn["outer"+a]=function(h){var k=this[0];return k?k.style?parseFloat(c.css(k,b,h?"margin":"border")):this[b]():null};c.fn[b]=function(h){return c.access(this,function(k,i,l){if(c.isWindow(k)){i=k.document;k=i.documentElement[d];return c.support.boxModel&&k||i.body&&
i.body[d]||k}if(k.nodeType===9){i=k.documentElement;if(i[d]>=i[e])return i[d];return Math.max(k.body[e],i[e],k.body[f],i[f])}if(l===A){k=c.css(k,i);i=parseFloat(k);return c.isNumeric(i)?i:k}c(k).css(i,l)},b,h,arguments.length,null)}});pjQ.jQuery=pjQ.$=c})(window);